/**
 * Additional Delicious Vietnamese & Asian Everyday Recipes for ChefMatch (Vét Tủ)
 */

const additionalRecipes = [
  {
    title: 'Cơm Chiên Kim Chi Trứng Ốp La',
    description: 'Tận dụng cơm nguội và hũ kim chi chua giòn làm món cơm chiên chuẩn vị Hàn Quốc.',
    imageUrl: 'https://images.unsplash.com/photo-1596560548464-f010549b84d7?q=80&w=800',
    prepTimeMinutes: 5,
    cookTimeMinutes: 10,
    servings: 2,
    difficulty: 'EASY',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Cơm nguội', normalized_name: 'com nguoi', quantity: '2', unit: 'bát', isOptional: false },
      { name: 'Kim chi', normalized_name: 'kim chi', quantity: '150', unit: 'gram', isOptional: false },
      { name: 'Trứng gà', normalized_name: 'trung ga', quantity: '2', unit: 'quả', isOptional: false },
      { name: 'Xúc xích', normalized_name: 'xuc xich', quantity: '1', unit: 'cây', isOptional: true },
      { name: 'Hành lá', normalized_name: 'hanh la', quantity: '2', unit: 'nhánh', isOptional: true },
      { name: 'Dầu mè', normalized_name: 'dau me', quantity: '1', unit: 'muỗng cà phê', isOptional: true },
    ],
    ingredientKeywords: ['cơm nguội', 'cơm', 'kim chi', 'trứng', 'trứng gà', 'xúc xích', 'hành lá', 'dầu mè'],
    instructions: [
      { stepNumber: 1, instruction: 'Kim chi và xúc xích cắt nhỏ hạt lựu. Hành lá cắt nhỏ.' },
      { stepNumber: 2, instruction: 'Ốp la 2 quả trứng lòng đào để riêng ra đĩa.' },
      { stepNumber: 3, instruction: 'Phi thơm đầu hành, cho xúc xích và kim chi vào xào thơm cùng 1 thìa nước kim chi.' },
      { stepNumber: 4, instruction: 'Đổ cơm nguội vào đảo tơi trên lửa lớn 5 phút, thêm dầu mè, rắc hành lá và đặt trứng ốp la lên trên.' },
    ],
  },
  {
    title: 'Canh Đậu Hũ Rong Biển Thịt Băm',
    description: 'Bát canh ngọt mát, thanh nhiệt cơ thể từ đậu hũ non và rong biển Hàn Quốc.',
    imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?q=80&w=800',
    prepTimeMinutes: 5,
    cookTimeMinutes: 10,
    servings: 3,
    difficulty: 'EASY',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Đậu hũ non', normalized_name: 'dau hu non', quantity: '1', unit: 'hộp', isOptional: false },
      { name: 'Rong biển khô', normalized_name: 'rong bien kho', quantity: '10', unit: 'gram', isOptional: false },
      { name: 'Thịt heo xay', normalized_name: 'thit heo xay', quantity: '100', unit: 'gram', isOptional: false },
      { name: 'Gừng', normalized_name: 'gung', quantity: '1', unit: 'nhánh nhỏ', isOptional: true },
      { name: 'Hành lá', normalized_name: 'hanh la', quantity: '1', unit: 'nhánh', isOptional: true },
    ],
    ingredientKeywords: ['đậu hũ non', 'đậu phụ', 'rong biển', 'thịt băm', 'thịt heo', 'gừng', 'hành lá'],
    instructions: [
      { stepNumber: 1, instruction: 'Rong biển ngâm nước 5 phút cho nở mềm rồi rửa sạch vắt ráo, cắt khúc nhỏ.' },
      { stepNumber: 2, instruction: 'Đậu hũ non cắt khối vuông vừa ăn. Gừng thái sợi.' },
      { stepNumber: 3, instruction: 'Xào săn thịt băm với chút dầu ăn và gừng, thêm 700ml nước đun sôi.' },
      { stepNumber: 4, instruction: 'Nước sôi thả rong biển và đậu hũ non vào, nêm hạt nêm vừa ăn, đun sôi lại 2 phút rồi rắc hành lá tắt bếp.' },
    ],
  },
  {
    title: 'Thịt Ba Chỉ Chiên Lắc Sả Tắc',
    description: 'Thịt ba chỉ chiên giòn rụm bên ngoài mềm ngọt bên trong, lắc cùng sả tắc chua cay mặn ngọt cực dính.',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=800',
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    servings: 3,
    difficulty: 'MEDIUM',
    appliance: 'AIR_FRYER',
    ingredients: [
      { name: 'Thịt ba chỉ', normalized_name: 'thit ba chi', quantity: '400', unit: 'gram', isOptional: false },
      { name: 'Sả', normalized_name: 'sa', quantity: '3', unit: 'cây', isOptional: false },
      { name: 'Quất (Tắc)', normalized_name: 'quat', quantity: '5', unit: 'quả', isOptional: false },
      { name: 'Ớt', normalized_name: 'ot', quantity: '2', unit: 'quả', isOptional: false },
      { name: 'Nước mắm', normalized_name: 'nuoc mam', quantity: '2', unit: 'muỗng canh', isOptional: false },
      { name: 'Đường', normalized_name: 'duong', quantity: '2', unit: 'muỗng canh', isOptional: false },
    ],
    ingredientKeywords: ['thịt ba chỉ', 'thịt heo', 'sả', 'quất', 'tắc', 'ớt', 'nước mắm', 'đường'],
    instructions: [
      { stepNumber: 1, instruction: 'Thịt ba chỉ rửa sạch, thái miếng dày 1cm. Ướp chút muối tiêu rồi cho vào nồi chiên không dầu 180°C trong 15 phút cho vàng giòn.' },
      { stepNumber: 2, instruction: 'Sả bào mỏng, quất thái lát bỏ hạt, ớt cắt lát.' },
      { stepNumber: 3, instruction: 'Pha sốt: 2 thìa nước mắm, 2 thìa đường, 1 thìa nước cốt quất, khuấy tan.' },
      { stepNumber: 4, instruction: 'Cho thịt chiên giòn, sả, quất lát, ớt và nước sốt vào âu đậy nắp lắc đều 30 giây rồi thưởng thức.' },
    ],
  },
  {
    title: 'Gà Sốt Me Chua Ngọt',
    description: 'Thịt gà chiên vàng ngập trong nước sốt me sánh quyện đậm đà cực đưa cơm.',
    imageUrl: 'https://images.unsplash.com/photo-1562967914-608f82629710?q=80&w=800',
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    servings: 3,
    difficulty: 'EASY',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Thịt gà', normalized_name: 'thit ga', quantity: '400', unit: 'gram', isOptional: false },
      { name: 'Nước cốt me', normalized_name: 'nuoc cot me', quantity: '3', unit: 'muỗng canh', isOptional: false },
      { name: 'Tỏi', normalized_name: 'toi', quantity: '3', unit: 'tép', isOptional: false },
      { name: 'Ớt', normalized_name: 'ot', quantity: '1', unit: 'quả', isOptional: true },
      { name: 'Hành lá', normalized_name: 'hanh la', quantity: '2', unit: 'nhánh', isOptional: true },
    ],
    ingredientKeywords: ['thịt gà', 'cánh gà', 'đùi gà', 'nước cốt me', 'me', 'tỏi', 'ớt', 'hành lá'],
    instructions: [
      { stepNumber: 1, instruction: 'Thịt gà chặt miếng vừa ăn, ướp chút hạt nêm tiêu trong 10 phút.' },
      { stepNumber: 2, instruction: 'Chiên thịt gà vàng giòn 2 mặt rồi vớt ra giấy thấm dầu.' },
      { stepNumber: 3, instruction: 'Phi thơm tỏi ớt băm, cho nước cốt me, 2 thìa đường, 2 thìa nước mắm và 2 thìa nước vào đun sôi sệt.' },
      { stepNumber: 4, instruction: 'Trút gà đã chiên vào đảo đều trên lửa nhỏ 3 phút cho sốt áo đều quanh miếng gà, rắc hành lá rồi tắt bếp.' },
    ],
  },
  {
    title: 'Cá Kho Tiêu Gừng Đậm Vị',
    description: 'Cá kho chắc thịt thơm lừng mùi gừng và tiêu đen cay nồng, ăn cùng cơm nóng ngày mưa.',
    imageUrl: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?q=80&w=800',
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    servings: 3,
    difficulty: 'MEDIUM',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Cá (Cá nục / Cá basa / Cá quả)', normalized_name: 'ca', quantity: '500', unit: 'gram', isOptional: false },
      { name: 'Gừng', normalized_name: 'gung', quantity: '1', unit: 'củ nhỏ', isOptional: false },
      { name: 'Hành tím', normalized_name: 'hanh tim', quantity: '2', unit: 'củ', isOptional: false },
      { name: 'Tiêu đen', normalized_name: 'tieu den', quantity: '1', unit: 'muỗng canh', isOptional: false },
      { name: 'Nước mắm', normalized_name: 'nuoc mam', quantity: '3', unit: 'muỗng canh', isOptional: false },
      { name: 'Ớt', normalized_name: 'ot', quantity: '2', unit: 'quả', isOptional: true },
    ],
    ingredientKeywords: ['cá', 'cá nục', 'cá basa', 'cá thu', 'gừng', 'hành tím', 'tiêu', 'nước mắm', 'ớt'],
    instructions: [
      { stepNumber: 1, instruction: 'Cá làm sạch, cắt khúc vừa ăn, rửa qua nước muối loãng để ráo.' },
      { stepNumber: 2, instruction: 'Ướp cá với hành gừng băm, 3 thìa nước mắm, 1 thìa đường, 1 thìa dầu ăn, 1 thìa tiêu trong 15 phút.' },
      { stepNumber: 3, instruction: 'Thắng 1 thìa đường làm nước màu cánh gián, xếp cá và gừng thái lát vào nồi đun săn 3 phút.' },
      { stepNumber: 4, instruction: 'Thêm 1 chén nước sôi xâm xấp mặt cá, đun nhỏ lửa 20 phút đến khi nước kho sánh keo lại, rắc thêm tiêu xay.' },
    ],
  },
  {
    title: 'Canh Bí Đao Nấu Tôm Tươi',
    description: 'Món canh thanh đạm, ngọt lịm tự nhiên từ tôm tươi và bí đao xanh mát.',
    imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?q=80&w=800',
    prepTimeMinutes: 5,
    cookTimeMinutes: 8,
    servings: 3,
    difficulty: 'EASY',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Bí đao', normalized_name: 'bi dao', quantity: '1', unit: 'trái nhỏ (300g)', isOptional: false },
      { name: 'Tôm tươi', normalized_name: 'tom tuoi', quantity: '150', unit: 'gram', isOptional: false },
      { name: 'Hành tím', normalized_name: 'hanh tim', quantity: '1', unit: 'củ', isOptional: true },
      { name: 'Hành lá, Mùi tàu', normalized_name: 'hanh la', quantity: '2', unit: 'nhánh', isOptional: true },
    ],
    ingredientKeywords: ['bí đao', 'tôm', 'tôm tươi', 'hành tím', 'hành lá', 'mùi tàu'],
    instructions: [
      { stepNumber: 1, instruction: 'Bí đao gọt vỏ, bỏ ruột, thái lát mỏng vừa ăn.' },
      { stepNumber: 2, instruction: 'Tôm bóc vỏ, bỏ chỉ lưng, giã dập hoặc băm nhỏ, ướp chút tiêu và hạt nêm.' },
      { stepNumber: 3, instruction: 'Phi thơm hành tím, cho tôm vào xào săn rồi đổ 700ml nước vào đun sôi.' },
      { stepNumber: 4, instruction: 'Nước sôi hớt bọt, thả bí đao vào nấu 2-3 phút cho bí vừa chín trong, nêm vừa miệng rồi rắc hành mùi tàu tắt bếp.' },
    ],
  },
  {
    title: 'Sườn Xào Chua Ngọt Chuẩn Vị',
    description: 'Miếng sườn mềm róc xương, sốt óng ánh vàng nâu chua dịu ngọt thanh thơm lừng.',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=800',
    prepTimeMinutes: 10,
    cookTimeMinutes: 20,
    servings: 3,
    difficulty: 'MEDIUM',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Sườn heo', normalized_name: 'suon heo', quantity: '500', unit: 'gram', isOptional: false },
      { name: 'Cà chua', normalized_name: 'ca chua', quantity: '1', unit: 'quả', isOptional: true },
      { name: 'Giấm gạo (hoặc chanh)', normalized_name: 'giam', quantity: '2', unit: 'muỗng canh', isOptional: false },
      { name: 'Đường', normalized_name: 'duong', quantity: '2', unit: 'muỗng canh', isOptional: false },
      { name: 'Nước mắm', normalized_name: 'nuoc mam', quantity: '2', unit: 'muỗng canh', isOptional: false },
      { name: 'Tỏi, Hành tím', normalized_name: 'toi', quantity: '3', unit: 'tép', isOptional: false },
    ],
    ingredientKeywords: ['sườn', 'sườn heo', 'sườn non', 'cà chua', 'giấm', 'đường', 'nước mắm', 'tỏi', 'hành tím'],
    instructions: [
      { stepNumber: 1, instruction: 'Sườn chặt khúc vừa ăn, chần qua nước sôi rửa sạch, ướp chút hạt nêm tiêu trong 10 phút.' },
      { stepNumber: 2, instruction: 'Chiên sườn vàng đều các mặt rồi vớt ra.' },
      { stepNumber: 3, instruction: 'Pha sốt chua ngọt: 2 thìa đường, 2 thìa giấm, 2 thìa nước mắm, 2 thìa tương cà/cà chua băm nhỏ và 3 thìa nước.' },
      { stepNumber: 4, instruction: 'Phi thơm hành tỏi, đổ nước sốt vào đun sôi rồi thả sườn vào đun nhỏ lửa 10 phút đến khi sốt sánh sệt bao bọc miếng sườn.' },
    ],
  },
  {
    title: 'Trứng Cuộn Phô Mai Rong Biển',
    description: 'Trứng mềm thơm xốp bọc lớp phô mai béo ngậy kéo sợi và rong biển giòn thơm.',
    imageUrl: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?q=80&w=800',
    prepTimeMinutes: 5,
    cookTimeMinutes: 8,
    servings: 2,
    difficulty: 'EASY',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Trứng gà', normalized_name: 'trung ga', quantity: '4', unit: 'quả', isOptional: false },
      { name: 'Phô mai lát (hoặc phô mai sợi)', normalized_name: 'pho mai', quantity: '2', unit: 'lát', isOptional: false },
      { name: 'Rong biển lá', normalized_name: 'rong bien', quantity: '1', unit: 'lá', isOptional: false },
      { name: 'Sữa tươi không đường', normalized_name: 'sua tuoi', quantity: '2', unit: 'muỗng canh', isOptional: true },
      { name: 'Cà rốt', normalized_name: 'ca rot', quantity: '20', unit: 'gram', isOptional: true },
    ],
    ingredientKeywords: ['trứng', 'trứng gà', 'phô mai', 'rong biển', 'sữa tươi', 'cà rốt'],
    instructions: [
      { stepNumber: 1, instruction: 'Đập 4 quả trứng, thêm 2 thìa sữa tươi, cà rốt băm nhỏ và 1/2 thìa hạt nêm, đánh tan đều.' },
      { stepNumber: 2, instruction: 'Lau chảo chống dính với lớp dầu mỏng, bật lửa nhỏ, đổ 1 lớp trứng mỏng dàn đều chảo.' },
      { stepNumber: 3, instruction: 'Khi trứng se mặt, đặt lá rong biển và phô mai lên trên rồi cuộn tròn trứng về một phía.' },
      { stepNumber: 4, instruction: 'Đổ tiếp lớp trứng tiếp theo vào mép nối, tiếp tục cuộn đến khi hết trứng. Cắt khoanh tròn vừa ăn.' },
    ],
  },
  {
    title: 'Bò Né Bánh Mì Trứng Pate',
    description: 'Bữa sáng / bữa tối siêu nhanh với chảo bò né bơ tỏi thơm lừng, trứng ốp la béo ngậy ăn kèm bánh mì.',
    imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?q=80&w=800',
    prepTimeMinutes: 8,
    cookTimeMinutes: 5,
    servings: 1,
    difficulty: 'EASY',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Thịt bò', normalized_name: 'thit bo', quantity: '150', unit: 'gram', isOptional: false },
      { name: 'Trứng gà', normalized_name: 'trung ga', quantity: '1', unit: 'quả', isOptional: false },
      { name: 'Pate', normalized_name: 'pate', quantity: '30', unit: 'gram', isOptional: true },
      { name: 'Bơ thực vật', normalized_name: 'bo', quantity: '1', unit: 'muỗng cà phê', isOptional: false },
      { name: 'Hành tây', normalized_name: 'hanh tay', quantity: '1/2', unit: 'củ', isOptional: true },
      { name: 'Bánh mì', normalized_name: 'banh mi', quantity: '1', unit: 'ổ', isOptional: false },
    ],
    ingredientKeywords: ['thịt bò', 'trứng', 'trứng gà', 'pate', 'bơ', 'hành tây', 'bánh mì'],
    instructions: [
      { stepNumber: 1, instruction: 'Thịt bò thái mỏng ướp tỏi băm, dầu hào, tiêu và 1 thìa dầu ăn cho mềm thịt.' },
      { stepNumber: 2, instruction: 'Làm nóng chảo gang với lửa lớn, cho bơ thực vật vào tan chảy thơm nức.' },
      { stepNumber: 3, instruction: 'Cho thịt bò và hành tây vào né nhanh trong 1 phút, đập 1 quả trứng ốp la bên cạnh và cho miếng pate vào.' },
      { stepNumber: 4, instruction: 'Rắc thêm tiêu đen, tắt bếp khi trứng còn lòng đào và ăn nóng kèm bánh mì giòn.' },
    ],
  },
  {
    title: 'Gỏi Gà Xé Phay Hành Tây Rau Răm',
    description: 'Gỏi gà chua ngọt thanh mát, thịt gà ngọt dai quyện hành tây giòn sần sật không hề hăng.',
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?q=80&w=800',
    prepTimeMinutes: 15,
    cookTimeMinutes: 0,
    servings: 3,
    difficulty: 'EASY',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Thịt gà luộc', normalized_name: 'thit ga', quantity: '300', unit: 'gram', isOptional: false },
      { name: 'Hành tây', normalized_name: 'hanh tay', quantity: '1', unit: 'củ', isOptional: false },
      { name: 'Rau răm', normalized_name: 'rau ram', quantity: '1', unit: 'nắm nhỏ', isOptional: false },
      { name: 'Chanh / Quất', normalized_name: 'chanh', quantity: '2', unit: 'quả', isOptional: false },
      { name: 'Đậu phộng (Lạc rang)', normalized_name: 'dau phong', quantity: '30', unit: 'gram', isOptional: true },
      { name: 'Ớt', normalized_name: 'ot', quantity: '1', unit: 'quả', isOptional: true },
    ],
    ingredientKeywords: ['thịt gà', 'gà luộc', 'hành tây', 'rau răm', 'chanh', 'đậu phộng', 'lạc', 'ớt'],
    instructions: [
      { stepNumber: 1, instruction: 'Thịt gà xé miếng vừa ăn. Hành tây thái mỏng ngâm vào âu nước đá lạnh có pha chút giấm đường 10 phút cho giòn ngọt.' },
      { stepNumber: 2, instruction: 'Pha nước trộn: 2 thìa nước cốt chanh, 2 thìa đường, 1.5 thìa nước mắm, tiêu và ớt băm khuấy tan.' },
      { stepNumber: 3, instruction: 'Vớt hành tây để ráo, cho thịt gà, hành tây, rau răm cắt khúc vào âu lớn.' },
      { stepNumber: 4, instruction: 'Rưới nước trộn gỏi vào bóp nhẹ tay cho thấm đều gia vị, bày ra đĩa rắc đậu phộng rang lên trên.' },
    ],
  },
  {
    title: 'Canh Khổ Qua Nhồi Thịt Thanh Nhiệt',
    description: 'Vị đắng nhẹ đầu lưỡi ngọt hậu thanh mát, nhân thịt băm mộc nhĩ thơm bùi.',
    imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?q=80&w=800',
    prepTimeMinutes: 15,
    cookTimeMinutes: 20,
    servings: 3,
    difficulty: 'MEDIUM',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Khổ qua (Mướp đắng)', normalized_name: 'kho qua', quantity: '2', unit: 'trái', isOptional: false },
      { name: 'Thịt heo xay', normalized_name: 'thit heo xay', quantity: '200', unit: 'gram', isOptional: false },
      { name: 'Mộc nhĩ (Nấm mèo)', normalized_name: 'moc nhi', quantity: '2', unit: 'tai', isOptional: true },
      { name: 'Hành tím, Hành lá', normalized_name: 'hanh tim', quantity: '2', unit: 'củ', isOptional: false },
      { name: 'Tiêu', normalized_name: 'tieu', quantity: '1/2', unit: 'muỗng cà phê', isOptional: true },
    ],
    ingredientKeywords: ['khổ qua', 'mướp đắng', 'thịt băm', 'thịt heo', 'mộc nhĩ', 'nấm mèo', 'hành lá', 'tiêu'],
    instructions: [
      { stepNumber: 1, instruction: 'Khổ qua cắt khúc 3-4cm, dùng thìa móc sạch ruột trắng.' },
      { stepNumber: 2, instruction: 'Mộc nhĩ ngâm nở băm nhỏ. Trộn thịt xay, mộc nhĩ, hành tím băm, hạt nêm và tiêu thật đều.' },
      { stepNumber: 3, instruction: 'Nhồi nhân thịt vào từng khúc khổ qua cho đầy đặn.' },
      { stepNumber: 4, instruction: 'Đun sôi 800ml nước, nhẹ nhàng thả khổ qua vào hầm nhỏ lửa 15-20 phút cho khổ qua mềm ngọt, nêm nếm vừa ăn và rắc hành lá.' },
    ],
  },
  {
    title: 'Nấm Đùi Gà Kho Tiêu Chay Đậm Đà',
    description: 'Nấm đùi gà giòn ngọt ngấm nước sốt tương tiêu đen cay nồng, món chay thanh tịnh siêu bắt cơm.',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800',
    prepTimeMinutes: 5,
    cookTimeMinutes: 12,
    servings: 2,
    difficulty: 'EASY',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Nấm đùi gà', normalized_name: 'nam dui ga', quantity: '300', unit: 'gram', isOptional: false },
      { name: 'Nước tương', normalized_name: 'nuoc tuong', quantity: '3', unit: 'muỗng canh', isOptional: false },
      { name: 'Đường', normalized_name: 'duong', quantity: '1.5', unit: 'muỗng canh', isOptional: false },
      { name: 'Tiêu đen xay', normalized_name: 'tieu den', quantity: '1', unit: 'muỗng canh', isOptional: false },
      { name: 'Hành boaro (hoặc tỏi)', normalized_name: 'hanh boaro', quantity: '1', unit: 'nhánh', isOptional: true },
      { name: 'Ớt', normalized_name: 'ot', quantity: '1', unit: 'quả', isOptional: true },
    ],
    ingredientKeywords: ['nấm đùi gà', 'nấm', 'nước tương', 'tiêu', 'đường', 'hành boaro', 'tỏi', 'ớt'],
    instructions: [
      { stepNumber: 1, instruction: 'Nấm đùi gà rửa sạch, cắt khoanh tròn dày 1.5cm, khía vảy rồng trên bề mặt để dễ ngấm gia vị.' },
      { stepNumber: 2, instruction: 'Áp chảo nấm với chút dầu ăn cho hai mặt xém vàng nhẹ.' },
      { stepNumber: 3, instruction: 'Phi thơm hành boaro/tỏi băm, cho 3 thìa nước tương, 1.5 thìa đường, 1/2 bát con nước và ớt vào đun sôi.' },
      { stepNumber: 4, instruction: 'Thả nấm vào kho nhỏ lửa 7-10 phút đến khi nước sốt cạn sệt lại, rắc thật nhiều tiêu đen rồi tắt bếp.' },
    ],
  },
  {
    title: 'Tôm Rim Thịt Ba Chỉ Cháy Cạnh',
    description: 'Tôm giòn ngọt vỏ kết hợp ba chỉ cháy cạnh béo ngậy mặn ngọt đậm đà, món ăn kinh điển gia đình Việt.',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=800',
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    servings: 3,
    difficulty: 'EASY',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Thịt ba chỉ', normalized_name: 'thit ba chi', quantity: '250', unit: 'gram', isOptional: false },
      { name: 'Tôm tươi', normalized_name: 'tom tuoi', quantity: '200', unit: 'gram', isOptional: false },
      { name: 'Hành tím, Tỏi', normalized_name: 'hanh tim', quantity: '2', unit: 'củ', isOptional: false },
      { name: 'Nước mắm', normalized_name: 'nuoc mam', quantity: '2', unit: 'muỗng canh', isOptional: false },
      { name: 'Đường', normalized_name: 'duong', quantity: '1.5', unit: 'muỗng canh', isOptional: false },
      { name: 'Hành lá, Tiêu', normalized_name: 'hanh la', quantity: '2', unit: 'nhánh', isOptional: true },
    ],
    ingredientKeywords: ['thịt ba chỉ', 'thịt heo', 'tôm', 'tôm tươi', 'hành tím', 'tỏi', 'nước mắm', 'đường', 'hành lá'],
    instructions: [
      { stepNumber: 1, instruction: 'Thịt ba chỉ cắt miếng con chì. Tôm cắt bỏ râu và đuôi nhọn, rửa sạch để ráo.' },
      { stepNumber: 2, instruction: 'Cho thịt ba chỉ vào chảo đảo lửa vừa cho ra bớt mỡ và xém vàng các cạnh, vớt bớt mỡ thừa ra.' },
      { stepNumber: 3, instruction: 'Phi thơm hành tỏi với thịt, trút tôm vào xào trên lửa lớn cho tôm chuyển màu đỏ au.' },
      { stepNumber: 4, instruction: 'Nêm 2 thìa nước mắm, 1.5 thìa đường, chút tiêu, đảo đều tay trên lửa nhỏ đến khi sốt keo bám bóng bẩy quanh tôm thịt, rắc hành lá tắt bếp.' },
    ],
  },
  {
    title: 'Bò Cuộn Nấm Kim Châm Nướng Nồi Chiên Không Dầu',
    description: 'Thịt ba chỉ bò Mỹ béo mềm cuộn nấm kim châm giòn ngọt, sốt dầu hào thơm phức.',
    imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?q=80&w=800',
    prepTimeMinutes: 10,
    cookTimeMinutes: 10,
    servings: 3,
    difficulty: 'EASY',
    appliance: 'AIR_FRYER',
    ingredients: [
      { name: 'Thịt ba chỉ bò', normalized_name: 'thit bo', quantity: '300', unit: 'gram', isOptional: false },
      { name: 'Nấm kim châm', normalized_name: 'nam kim cham', quantity: '1', unit: 'gói (200g)', isOptional: false },
      { name: 'Dầu hào', normalized_name: 'dau hao', quantity: '1', unit: 'muỗng canh', isOptional: false },
      { name: 'Nước tương', normalized_name: 'nuoc tuong', quantity: '1', unit: 'muỗng canh', isOptional: false },
      { name: 'Tiêu, Tỏi băm', normalized_name: 'tieu', quantity: '1/2', unit: 'muỗng cà phê', isOptional: true },
    ],
    ingredientKeywords: ['thịt bò', 'ba chỉ bò', 'nấm kim châm', 'nấm', 'dầu hào', 'nước tương', 'tiêu'],
    instructions: [
      { stepNumber: 1, instruction: 'Nấm kim châm cắt gốc, rửa sạch tách thành các cụm nhỏ.' },
      { stepNumber: 2, instruction: 'Trải từng lát thịt bò ra đĩa, đặt nấm kim châm vào một đầu rồi cuộn chặt tay.' },
      { stepNumber: 3, instruction: 'Pha sốt quét: 1 thìa dầu hào, 1 thìa nước tương, 1 thìa mật ong/đường, tỏi băm và tiêu.' },
      { stepNumber: 4, instruction: 'Xếp cuộn bò vào nồi chiên không dầu, quét sốt lên bề mặt, nướng 180°C trong 8-10 phút cho xém thơm vàng óng.' },
    ],
  },
  {
    title: 'Cánh Gà Chiên Nước Mắm Tỏi Ớt',
    description: 'Vỏ cánh gà giòn tan đậm đà mặn ngọt cay cay, tỏi phi thơm nức mũi.',
    imageUrl: 'https://images.unsplash.com/photo-1562967914-608f82629710?q=80&w=800',
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    servings: 3,
    difficulty: 'EASY',
    appliance: 'AIR_FRYER',
    ingredients: [
      { name: 'Cánh gà', normalized_name: 'canh ga', quantity: '500', unit: 'gram', isOptional: false },
      { name: 'Tỏi', normalized_name: 'toi', quantity: '1', unit: 'củ', isOptional: false },
      { name: 'Nước mắm', normalized_name: 'nuoc mam', quantity: '2', unit: 'muỗng canh', isOptional: false },
      { name: 'Đường', normalized_name: 'duong', quantity: '2', unit: 'muỗng canh', isOptional: false },
      { name: 'Bơ thực vật', normalized_name: 'bo', quantity: '1', unit: 'muỗng cà phê', isOptional: true },
      { name: 'Ớt', normalized_name: 'ot', quantity: '1', unit: 'quả', isOptional: true },
    ],
    ingredientKeywords: ['cánh gà', 'thịt gà', 'tỏi', 'nước mắm', 'đường', 'bơ', 'ớt'],
    instructions: [
      { stepNumber: 1, instruction: 'Cánh gà làm sạch, khía nhẹ mặt sau, ướp chút muối tiêu rồi chiên vàng giòn trong nồi chiên không dầu (190°C trong 15 phút).' },
      { stepNumber: 2, instruction: 'Tỏi băm nhỏ, ớt băm nhỏ.' },
      { stepNumber: 3, instruction: 'Làm nóng chảo, cho bơ và phi thơm vàng tỏi ớt, cho 2 thìa mắm, 2 thìa đường và 1 thìa nước vào nấu sôi sệt.' },
      { stepNumber: 4, instruction: 'Trút cánh gà chiên giòn vào đảo nhanh tay 1-2 phút cho nước sốt mắm tỏi bám đều lớp da giòn rồi tắt bếp.' },
    ],
  },
  {
    title: 'Chả Lá Lốt Thịt Heo Thơm Nức',
    description: 'Từng cuốn chả lá lốt xanh mướt, bên trong thịt ngọt mềm thơm lừng mùi lá lốt đặc trưng.',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=800',
    prepTimeMinutes: 15,
    cookTimeMinutes: 10,
    servings: 3,
    difficulty: 'EASY',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Thịt heo xay', normalized_name: 'thit heo xay', quantity: '300', unit: 'gram', isOptional: false },
      { name: 'Lá lốt', normalized_name: 'la lot', quantity: '20', unit: 'lá', isOptional: false },
      { name: 'Hành tím', normalized_name: 'hanh tim', quantity: '2', unit: 'củ', isOptional: false },
      { name: 'Hạt nêm, Tiêu', normalized_name: 'hat nem', quantity: '1', unit: 'muỗng cà phê', isOptional: false },
      { name: 'Dầu ăn', normalized_name: 'dau an', quantity: '2', unit: 'muỗng canh', isOptional: false },
    ],
    ingredientKeywords: ['lá lốt', 'thịt băm', 'thịt heo', 'hành tím', 'tiêu'],
    instructions: [
      { stepNumber: 1, instruction: 'Lá lốt rửa sạch để ráo, chọn lá nguyên đẹp để cuốn, lấy 2-3 lá nhỏ băm nhuyễn.' },
      { stepNumber: 2, instruction: 'Trộn thịt heo xay cùng hành tím băm, lá lốt băm, 1 thìa hạt nêm, tiêu và 1 thìa dầu ăn cho thịt mềm dẻo.' },
      { stepNumber: 3, instruction: 'Đặt mặt láng của lá lốt xuống dưới, cho lượng thịt vừa phải vào giữa rồi cuộn tròn chặt tay.' },
      { stepNumber: 4, instruction: 'Bắc chảo dầu lên bếp, cho chả lá lốt vào rán lửa nhỏ đều các mặt khoảng 7-8 phút cho chín thơm nức mũi.' },
    ],
  },
  {
    title: 'Salad Ức Gà Sốt Mè Rang Healthy',
    description: 'Ức gà áp chảo xé sợi trộn cùng rau xà lách, cà chua bi tươi giòn và sốt mè rang bùi béo.',
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?q=80&w=800',
    prepTimeMinutes: 10,
    cookTimeMinutes: 8,
    servings: 2,
    difficulty: 'EASY',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Ức gà', normalized_name: 'uc ga', quantity: '250', unit: 'gram', isOptional: false },
      { name: 'Xà lách', normalized_name: 'xa lach', quantity: '100', unit: 'gram', isOptional: false },
      { name: 'Cà chua bi (hoặc cà chua thường)', normalized_name: 'ca chua', quantity: '6', unit: 'quả', isOptional: false },
      { name: 'Dưa chuột', normalized_name: 'dua chuot', quantity: '1', unit: 'quả', isOptional: false },
      { name: 'Sốt mè rang', normalized_name: 'sot me rang', quantity: '3', unit: 'muỗng canh', isOptional: false },
    ],
    ingredientKeywords: ['ức gà', 'thịt gà', 'xà lách', 'cà chua', 'dưa chuột', 'sốt mè rang', 'salad'],
    instructions: [
      { stepNumber: 1, instruction: 'Ức gà ướp chút muối tiêu, áp chảo với 1 thìa dầu ô liu mỗi mặt 4-5 phút cho chín vàng mọng nước, để nguội xé sợi hoặc thái lát.' },
      { stepNumber: 2, instruction: 'Xà lách rửa sạch cắt khúc, dưa chuột thái lát, cà chua bi bổ đôi.' },
      { stepNumber: 3, instruction: 'Xếp rau xà lách, dưa chuột, cà chua bi vào đĩa sâu lòng, xếp ức gà lên trên.' },
      { stepNumber: 4, instruction: 'Rưới 3 thìa sốt mè rang lên trên và trộn đều trước khi thưởng thức.' },
    ],
  },
  {
    title: 'Đậu Phụ Nhồi Thịt Sốt Cà Chua',
    description: 'Đậu phụ vàng giòn bên ngoài nhồi nhân thịt mộc nhĩ ngọt béo, áo đều lớp sốt cà chua đỏ mọng.',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800',
    prepTimeMinutes: 15,
    cookTimeMinutes: 15,
    servings: 3,
    difficulty: 'MEDIUM',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Đậu phụ', normalized_name: 'dau phu', quantity: '4', unit: 'miếng', isOptional: false },
      { name: 'Thịt heo xay', normalized_name: 'thit heo xay', quantity: '150', unit: 'gram', isOptional: false },
      { name: 'Mộc nhĩ', normalized_name: 'moc nhi', quantity: '1', unit: 'tai', isOptional: true },
      { name: 'Cà chua', normalized_name: 'ca chua', quantity: '2', unit: 'quả', isOptional: false },
      { name: 'Hành lá, Hành tím', normalized_name: 'hanh la', quantity: '2', unit: 'nhánh', isOptional: false },
    ],
    ingredientKeywords: ['đậu phụ', 'đậu hũ', 'thịt băm', 'thịt heo', 'mộc nhĩ', 'cà chua', 'hành lá', 'hành tím'],
    instructions: [
      { stepNumber: 1, instruction: 'Đậu phụ chiên sơ, rạch một đường giữa thân hoặc khoét lỗ moi bớt ruột đậu.' },
      { stepNumber: 2, instruction: 'Trộn thịt xay, mộc nhĩ băm, ruột đậu, hành tím, tiêu hạt nêm rồi nhồi chặt vào trong miếng đậu.' },
      { stepNumber: 3, instruction: 'Áp chảo mặt thịt của miếng đậu cho săn vàng.' },
      { stepNumber: 4, instruction: 'Phi thơm hành, xào cà chua mềm nát thành sốt sệt, xếp đậu nhồi thịt vào rim nhỏ lửa 10 phút cho ngấm sốt, rắc hành lá tắt bếp.' },
    ],
  },
  {
    title: 'Bắp Cải Cuộn Thịt Hấp Ngọt Nước',
    description: 'Lá bắp cải cuộn nhân thịt hấp chín tới giữ trọn vẹn vị ngọt thanh mát tự nhiên.',
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?q=80&w=800',
    prepTimeMinutes: 15,
    cookTimeMinutes: 15,
    servings: 3,
    difficulty: 'MEDIUM',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Bắp cải', normalized_name: 'bap cai', quantity: '1/2', unit: 'bắp', isOptional: false },
      { name: 'Thịt heo xay', normalized_name: 'thit heo xay', quantity: '200', unit: 'gram', isOptional: false },
      { name: 'Mộc nhĩ', normalized_name: 'moc nhi', quantity: '2', unit: 'tai', isOptional: true },
      { name: 'Cà rốt', normalized_name: 'ca rot', quantity: '1/3', unit: 'củ', isOptional: true },
      { name: 'Hành lá', normalized_name: 'hanh la', quantity: '5', unit: 'cọng', isOptional: false },
    ],
    ingredientKeywords: ['bắp cải', 'thịt băm', 'thịt heo', 'mộc nhĩ', 'cà rốt', 'hành lá'],
    instructions: [
      { stepNumber: 1, instruction: 'Bắp cải tách từng lá to nguyên vẹn, chần sơ qua nước sôi 1 phút cho mềm dai dễ cuốn. Chần sơ cọng hành lá để làm dây buộc.' },
      { stepNumber: 2, instruction: 'Trộn thịt băm với mộc nhĩ, cà rốt băm nhỏ, hạt nêm tiêu.' },
      { stepNumber: 3, instruction: 'Trải lá bắp cải, cho thịt vào cuộn tròn như cuốn nem, dùng cọng hành lá buộc nhẹ ở giữa.' },
      { stepNumber: 4, instruction: 'Xếp các cuộn bắp cải vào xửng hấp cách thủy 15 phút là chín ngọt mềm, chấm cùng nước tương tỏi ớt.' },
    ],
  },
  {
    title: 'Canh Kim Chi Đậu Hũ Thịt Heo Cay Nồng',
    description: 'Canh kim chi chuẩn vị Hàn Quốc cay nồng chua dịu, thịt ba chỉ béo ngậy đậu hũ mềm mịn.',
    imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?q=80&w=800',
    prepTimeMinutes: 5,
    cookTimeMinutes: 12,
    servings: 3,
    difficulty: 'EASY',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Kim chi', normalized_name: 'kim chi', quantity: '200', unit: 'gram', isOptional: false },
      { name: 'Thịt ba chỉ', normalized_name: 'thit ba chi', quantity: '150', unit: 'gram', isOptional: false },
      { name: 'Đậu phụ', normalized_name: 'dau phu', quantity: '2', unit: 'miếng', isOptional: false },
      { name: 'Nấm kim châm', normalized_name: 'nam kim cham', quantity: '100', unit: 'gram', isOptional: true },
      { name: 'Hành lá', normalized_name: 'hanh la', quantity: '2', unit: 'nhánh', isOptional: true },
      { name: 'Tỏi', normalized_name: 'toi', quantity: '2', unit: 'tép', isOptional: true },
    ],
    ingredientKeywords: ['kim chi', 'thịt ba chỉ', 'thịt heo', 'đậu phụ', 'đậu hũ', 'nấm kim châm', 'hành lá', 'tỏi'],
    instructions: [
      { stepNumber: 1, instruction: 'Thịt ba chỉ thái mỏng. Đậu phụ cắt miếng vuông. Kim chi cắt khúc vừa ăn.' },
      { stepNumber: 2, instruction: 'Phi thơm tỏi băm, cho thịt ba chỉ vào xào săn, tiếp tục cho kim chi vào xào 2 phút cho dậy mùi thơm.' },
      { stepNumber: 3, instruction: 'Đổ 600ml nước cùng 3 thìa nước cốt kim chi vào đun sôi bùng lên.' },
      { stepNumber: 4, instruction: 'Thả đậu phụ và nấm kim châm vào nấu thêm 3 phút, nêm chút hạt nêm nước tương vừa miệng, rắc hành lá tắt bếp.' },
    ],
  },
  {
    title: 'Bánh Mì Chảo Trứng Xúc Xích Bơ Tỏi',
    description: 'Chảo bánh mì nóng hổi thơm nức mùi bơ, trứng ốp la lòng đào, xúc xích và sốt cà chua sánh mịn.',
    imageUrl: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?q=80&w=800',
    prepTimeMinutes: 5,
    cookTimeMinutes: 8,
    servings: 1,
    difficulty: 'EASY',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Bánh mì', normalized_name: 'banh mi', quantity: '1', unit: 'ổ', isOptional: false },
      { name: 'Trứng gà', normalized_name: 'trung ga', quantity: '2', unit: 'quả', isOptional: false },
      { name: 'Xúc xích', normalized_name: 'xuc xich', quantity: '1', unit: 'cây', isOptional: false },
      { name: 'Cà chua', normalized_name: 'ca chua', quantity: '1', unit: 'quả', isOptional: false },
      { name: 'Bơ', normalized_name: 'bo', quantity: '1', unit: 'muỗng cà phê', isOptional: false },
      { name: 'Hành tây', normalized_name: 'hanh tay', quantity: '1/4', unit: 'củ', isOptional: true },
      { name: 'Pate', normalized_name: 'pate', quantity: '20', unit: 'gram', isOptional: true },
    ],
    ingredientKeywords: ['bánh mì', 'trứng', 'trứng gà', 'xúc xích', 'cà chua', 'bơ', 'hành tây', 'pate'],
    instructions: [
      { stepNumber: 1, instruction: 'Xúc xích khía vảy rồng. Cà chua băm nhỏ xào nhuyễn với tỏi và chút đường làm sốt sệt.' },
      { stepNumber: 2, instruction: 'Làm nóng chảo nhỏ, cho bơ vào tan chảy, cho xúc xích vào chiên xém vàng.' },
      { stepNumber: 3, instruction: 'Đập 2 quả trứng gà vào chảo ốp la, múc sốt cà chua và miếng pate đặt bên cạnh.' },
      { stepNumber: 4, instruction: 'Rắc tiêu, vài cọng ngò rí lên trên, ăn ngay khi chảo còn xèo xèo cùng bánh mì nóng giòn.' },
    ],
  },
  {
    title: 'Canh Dưa Chua Nấu Thịt Bò',
    description: 'Bát canh dưa cải chua giòn, nước canh chua thanh ngọt đậm đà từ thịt bò mềm ngọt.',
    imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?q=80&w=800',
    prepTimeMinutes: 8,
    cookTimeMinutes: 12,
    servings: 3,
    difficulty: 'EASY',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Dưa cải chua', normalized_name: 'dua cai chua', quantity: '200', unit: 'gram', isOptional: false },
      { name: 'Thịt bò', normalized_name: 'thit bo', quantity: '200', unit: 'gram', isOptional: false },
      { name: 'Cà chua', normalized_name: 'ca chua', quantity: '2', unit: 'quả', isOptional: false },
      { name: 'Hành tím', normalized_name: 'hanh tim', quantity: '2', unit: 'củ', isOptional: false },
      { name: 'Hành lá, Thì là', normalized_name: 'hanh la', quantity: '2', unit: 'nhánh', isOptional: true },
    ],
    ingredientKeywords: ['dưa chua', 'dưa cải', 'thịt bò', 'cà chua', 'hành tím', 'hành lá', 'thì là'],
    instructions: [
      { stepNumber: 1, instruction: 'Thịt bò thái mỏng ướp chút tỏi băm, tiêu và dầu ăn. Dưa chua rửa sơ vắt ráo. Cà chua bổ múi cau.' },
      { stepNumber: 2, instruction: 'Phi thơm hành tím, xào cà chua mềm rồi trút dưa chua vào xào săn 3 phút với chút hạt nêm.' },
      { stepNumber: 3, instruction: 'Đổ 700ml nước vào đun sôi, hạ nhỏ lửa đun 10 phút cho dưa chua tiết vị ngọt chua ra nước canh.' },
      { stepNumber: 4, instruction: 'Tăng lửa lớn, thả thịt bò vào đảo nhanh 1 phút cho thịt vừa chín mềm ngọt, rắc hành lá thì là rồi tắt bếp.' },
    ],
  },
  {
    title: 'Cơm Lười Nồi Cơm Điện (Gà, Nấm & Lạp Xưởng)',
    description: 'Chỉ cần cho tất cả nguyên liệu vào nồi cơm điện bấm nút là có ngay bữa cơm thơm lừng chuẩn vị nhà hàng.',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800',
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    servings: 3,
    difficulty: 'EASY',
    appliance: 'RICE_COOKER',
    ingredients: [
      { name: 'Gạo tẻ', normalized_name: 'gao', quantity: '2', unit: 'bát con', isOptional: false },
      { name: 'Đùi gà / Ức gà', normalized_name: 'thit ga', quantity: '200', unit: 'gram', isOptional: false },
      { name: 'Nấm hương (hoặc nấm đông cô)', normalized_name: 'nam huong', quantity: '5', unit: 'tai', isOptional: true },
      { name: 'Lạp xưởng (hoặc xúc xích)', normalized_name: 'lap xuong', quantity: '1', unit: 'cây', isOptional: true },
      { name: 'Cà rốt', normalized_name: 'ca rot', quantity: '1/2', unit: 'củ', isOptional: true },
      { name: 'Dầu hào, Nước tương', normalized_name: 'dau hao', quantity: '1', unit: 'muỗng canh', isOptional: false },
    ],
    ingredientKeywords: ['gạo', 'cơm', 'thịt gà', 'đùi gà', 'nấm hương', 'lạp xưởng', 'xúc xích', 'cà rốt', 'dầu hào'],
    instructions: [
      { stepNumber: 1, instruction: 'Gạo vo sạch cho vào nồi cơm với lượng nước ít hơn bình thường một chút.' },
      { stepNumber: 2, instruction: 'Gà cắt miếng vuông, ướp với 1 thìa dầu hào, 1 thìa nước tương, chút dầu mè và tiêu trong 10 phút.' },
      { stepNumber: 3, instruction: 'Nấm hương ngâm nở thái lát, cà rốt thái hạt lựu, lạp xưởng thái lát chéo.' },
      { stepNumber: 4, instruction: 'Xếp tất cả gà, nấm, cà rốt, lạp xưởng lên mặt gạo, bấm nút nấu cơm bình thường. Khi cơm chín xới đều là có món cơm trộn siêu thơm ngọt.' },
    ],
  },
  {
    title: 'Trứng Hấp Kiểu Nhật (Chawanmushi) Mịn Mượt',
    description: 'Bát trứng hấp láng mịn như thạch, tan ngay trong miệng với tôm ngọt và nấm thơm.',
    imageUrl: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?q=80&w=800',
    prepTimeMinutes: 5,
    cookTimeMinutes: 12,
    servings: 2,
    difficulty: 'EASY',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Trứng gà', normalized_name: 'trung ga', quantity: '2', unit: 'quả', isOptional: false },
      { name: 'Nước luộc gà (hoặc nước ấm)', normalized_name: 'nuoc dung', quantity: '200', unit: 'ml', isOptional: false },
      { name: 'Tôm tươi', normalized_name: 'tom', quantity: '2', unit: 'con', isOptional: true },
      { name: 'Nấm hương / Nấm đông cô', normalized_name: 'nam', quantity: '2', unit: 'tai', isOptional: true },
      { name: 'Nước tương, Muối', normalized_name: 'nuoc tuong', quantity: '1/2', unit: 'muỗng cà phê', isOptional: false },
    ],
    ingredientKeywords: ['trứng', 'trứng gà', 'tôm', 'nấm', 'nước tương'],
    instructions: [
      { stepNumber: 1, instruction: 'Đập trứng ra tô, đánh tan nhẹ tay (tránh tạo bọt khí).' },
      { stepNumber: 2, instruction: 'Pha nước dùng ấm với 1/2 thìa nước tương, chút muối rồi đổ từ từ vào trứng khuấy đều.' },
      { stepNumber: 3, instruction: 'Lọc hỗn hợp trứng qua rây 2 lần cho thật mịn, rót vào chén/bát sứ.' },
      { stepNumber: 4, instruction: 'Đặt tôm và nấm lên trên, bọc màng bọc thực phẩm hoặc đậy nắp, hấp lửa thật nhỏ trong 12-15 phút đến khi mặt trứng láng mịn hoàn hảo.' },
    ],
  },
  {
    title: 'Mực Xào Sa Tế Cần Tỏi Giòn Cay',
    description: 'Mực tươi giòn sần sật quyện vị sa tế cay nồng, cần tây và tỏi tây thơm lừng.',
    imageUrl: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?q=80&w=800',
    prepTimeMinutes: 10,
    cookTimeMinutes: 6,
    servings: 3,
    difficulty: 'EASY',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Mực tươi', normalized_name: 'muc tuoi', quantity: '300', unit: 'gram', isOptional: false },
      { name: 'Sa tế', normalized_name: 'sa te', quantity: '1.5', unit: 'muỗng canh', isOptional: false },
      { name: 'Cần tây, Tỏi tây', normalized_name: 'can tay', quantity: '2', unit: 'cây', isOptional: false },
      { name: 'Hành tây', normalized_name: 'hanh tay', quantity: '1/2', unit: 'củ', isOptional: false },
      { name: 'Tỏi', normalized_name: 'toi', quantity: '3', unit: 'tép', isOptional: false },
    ],
    ingredientKeywords: ['mực', 'mực tươi', 'sa tế', 'cần tây', 'tỏi tây', 'hành tây', 'tỏi'],
    instructions: [
      { stepNumber: 1, instruction: 'Mực làm sạch, khía vảy rồng, cắt miếng vừa ăn, chần sơ nước sôi có gừng trong 20 giây rồi vớt ra ngay.' },
      { stepNumber: 2, instruction: 'Cần tỏi tây rửa sạch cắt khúc 4cm, hành tây bổ múi cau.' },
      { stepNumber: 3, instruction: 'Phi thơm tỏi băm với 1.5 thìa sa tế, bật lửa lớn trút mực vào đảo nhanh 1 phút.' },
      { stepNumber: 4, instruction: 'Cho tiếp cần tỏi và hành tây vào đảo đều tay trên lửa lớn 2 phút, nêm chút dầu hào và nước mắm rồi tắt bếp.' },
    ],
  },
  {
    title: 'Trứng Cút Lộn Xào Me Chua Cay',
    description: 'Món ăn vặt đường phố nổi tiếng với vị chua ngọt đậm đà từ sốt me quyện trứng cút bùi béo.',
    imageUrl: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?q=80&w=800',
    prepTimeMinutes: 10,
    cookTimeMinutes: 10,
    servings: 2,
    difficulty: 'EASY',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Trứng cút lộn', normalized_name: 'trung cut lon', quantity: '15', unit: 'quả', isOptional: false },
      { name: 'Nước cốt me', normalized_name: 'nuoc cot me', quantity: '3', unit: 'muỗng canh', isOptional: false },
      { name: 'Rau răm', normalized_name: 'rau ram', quantity: '1', unit: 'nắm nhỏ', isOptional: false },
      { name: 'Đậu phộng (Lạc rang)', normalized_name: 'dau phong', quantity: '20', unit: 'gram', isOptional: true },
      { name: 'Tỏi, Ớt', normalized_name: 'toi', quantity: '3', unit: 'tép', isOptional: false },
      { name: 'Đường, Nước mắm', normalized_name: 'duong', quantity: '2', unit: 'muỗng canh', isOptional: false },
    ],
    ingredientKeywords: ['trứng cút', 'trứng cút lộn', 'nước cốt me', 'me', 'rau răm', 'đậu phộng', 'tỏi', 'ớt'],
    instructions: [
      { stepNumber: 1, instruction: 'Trứng cút lộn luộc chín 8 phút, ngâm nước lạnh rồi bóc sạch vỏ nhẹ tay.' },
      { stepNumber: 2, instruction: 'Phi thơm tỏi ớt băm, cho nước cốt me, 2 thìa đường, 2 thìa nước mắm và 2 thìa nước lọc vào đun sôi sệt.' },
      { stepNumber: 3, instruction: 'Thả trứng cút lộn vào rim nhỏ lửa 3-4 phút cho nước sốt me áo đều từng quả trứng.' },
      { stepNumber: 4, instruction: 'Múc ra đĩa, rắc đậu phộng rang giã dập, hành phi và ăn kèm rau răm tươi.' },
    ],
  },
  {
    title: 'Cháo Thịt Bằm Trứng Bắc Thảo',
    description: 'Bát cháo nóng hổi sánh mịn, ngọt nước từ thịt bằm, trứng bắc thảo bùi béo dậy mùi tiêu gừng.',
    imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?q=80&w=800',
    prepTimeMinutes: 10,
    cookTimeMinutes: 30,
    servings: 3,
    difficulty: 'EASY',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Gạo tẻ', normalized_name: 'gao', quantity: '1/2', unit: 'bát con', isOptional: false },
      { name: 'Thịt heo xay', normalized_name: 'thit heo xay', quantity: '150', unit: 'gram', isOptional: false },
      { name: 'Trứng bắc thảo', normalized_name: 'trung bac thao', quantity: '2', unit: 'quả', isOptional: false },
      { name: 'Gừng', normalized_name: 'gung', quantity: '1', unit: 'nhánh nhỏ', isOptional: true },
      { name: 'Hành lá, Ngò rí', normalized_name: 'hanh la', quantity: '2', unit: 'nhánh', isOptional: true },
      { name: 'Tiêu', normalized_name: 'tieu', quantity: '1/2', unit: 'muỗng cà phê', isOptional: true },
    ],
    ingredientKeywords: ['gạo', 'cháo', 'thịt băm', 'thịt heo', 'trứng bắc thảo', 'gừng', 'hành lá', 'tiêu'],
    instructions: [
      { stepNumber: 1, instruction: 'Gạo vo sạch, ninh với 1 lít nước trên lửa vừa đến khi hạt gạo nở bung sánh mịn.' },
      { stepNumber: 2, instruction: 'Thịt băm ướp chút hạt nêm, tiêu và hành tím băm, xào sơ cho săn.' },
      { stepNumber: 3, instruction: 'Trứng bắc thảo bóc vỏ, cắt hạt lựu hoặc múi cau.' },
      { stepNumber: 4, instruction: 'Cho thịt băm và trứng bắc thảo vào nồi cháo khuấy đều đun sôi lại 5 phút, nêm vừa ăn, múc ra tô rắc gừng thái sợi, hành lá và tiêu đen.' },
    ],
  },
];

module.exports = additionalRecipes;

