const recipes = [
  {
    title: 'Trứng Chiên Cà Chua',
    description: 'Món ăn quốc dân nhanh gọn, bổ dưỡng, chua ngọt đậm đà cực đưa cơm.',
    imageUrl: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?q=80&w=800',
    prepTimeMinutes: 5,
    cookTimeMinutes: 10,
    servings: 2,
    difficulty: 'EASY',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Trứng gà', normalized_name: 'trung ga', quantity: '3', unit: 'quả', isOptional: false },
      { name: 'Cà chua', normalized_name: 'ca chua', quantity: '2', unit: 'quả', isOptional: false },
      { name: 'Hành lá', normalized_name: 'hanh la', quantity: '2', unit: 'nhánh', isOptional: false },
      { name: 'Hành tím', normalized_name: 'hanh tim', quantity: '1', unit: 'củ', isOptional: true },
      { name: 'Nước mắm', normalized_name: 'nuoc mam', quantity: '1', unit: 'muỗng canh', isOptional: true },
    ],
    ingredientKeywords: ['trứng', 'trứng gà', 'cà chua', 'hành lá', 'hành tím', 'nước mắm'],
    instructions: [
      { stepNumber: 1, instruction: 'Cà chua rửa sạch, thái múi cau. Hành lá cắt nhỏ, hành tím băm nhuyễn.' },
      { stepNumber: 2, instruction: 'Đập 3 quả trứng vào tô, thêm 1/2 thìa hạt nêm, tiêu và hành lá, đánh tan đều.' },
      { stepNumber: 3, instruction: 'Phi thơm hành tím với 1 thìa dầu ăn, cho cà chua vào xào mềm cho ra nước sốt đỏ.' },
      { stepNumber: 4, instruction: 'Đổ từ từ trứng vào chảo, để lửa nhỏ, đảo nhẹ tay cho trứng đông sệt lại rồi tắt bếp.' },
    ],
  },
  {
    title: 'Đậu Hũ Sốt Cà Chua',
    description: 'Đậu hũ chiên giòn quyện cùng sốt cà chua thơm nức mùi hành hoa.',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800',
    prepTimeMinutes: 5,
    cookTimeMinutes: 12,
    servings: 2,
    difficulty: 'EASY',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Đậu phụ', normalized_name: 'dau phu', quantity: '3', unit: 'miếng', isOptional: false },
      { name: 'Cà chua', normalized_name: 'ca chua', quantity: '2', unit: 'quả', isOptional: false },
      { name: 'Hành lá', normalized_name: 'hanh la', quantity: '2', unit: 'nhánh', isOptional: false },
      { name: 'Tỏi', normalized_name: 'toi', quantity: '2', unit: 'tép', isOptional: true },
      { name: 'Nước mắm', normalized_name: 'nuoc mam', quantity: '1', unit: 'muỗng canh', isOptional: true },
    ],
    ingredientKeywords: ['đậu phụ', 'đậu hũ', 'cà chua', 'hành lá', 'tỏi', 'nước mắm'],
    instructions: [
      { stepNumber: 1, instruction: 'Đậu phụ cắt miếng vuông vừa ăn, chiên vàng giòn các mặt rồi vớt ra đĩa.' },
      { stepNumber: 2, instruction: 'Cà chua băm nhỏ. Phi thơm tỏi băm, cho cà chua vào xào nhuyễn thành sốt sệt.' },
      { stepNumber: 3, instruction: 'Nêm 1 thìa nước mắm, 1 thìa đường, chút tiêu rồi cho đậu phụ đã chiên vào đảo đều.' },
      { stepNumber: 4, instruction: 'Đun nhỏ lửa 3-5 phút cho đậu ngấm sốt, rắc hành lá cắt nhỏ lên trên rồi tắt bếp.' },
    ],
  },
  {
    title: 'Thịt Bò Xào Hành Tây',
    description: 'Thịt bò mềm ngọt, hành tây giòn ngọt hòa quyện thơm nức mùi tiêu.',
    imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?q=80&w=800',
    prepTimeMinutes: 10,
    cookTimeMinutes: 8,
    servings: 3,
    difficulty: 'EASY',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Thịt bò', normalized_name: 'thit bo', quantity: '250', unit: 'gram', isOptional: false },
      { name: 'Hành tây', normalized_name: 'hanh tay', quantity: '1', unit: 'củ', isOptional: false },
      { name: 'Tỏi', normalized_name: 'toi', quantity: '3', unit: 'tép', isOptional: false },
      { name: 'Cần tây', normalized_name: 'can tay', quantity: '2', unit: 'nhánh', isOptional: true },
      { name: 'Dầu hào', normalized_name: 'dau hao', quantity: '1', unit: 'muỗng canh', isOptional: true },
      { name: 'Tiêu', normalized_name: 'tieu', quantity: '1/2', unit: 'muỗng cà phê', isOptional: true },
    ],
    ingredientKeywords: ['thịt bò', 'hành tây', 'tỏi', 'cần tây', 'dầu hào', 'tiêu'],
    instructions: [
      { stepNumber: 1, instruction: 'Thịt bò thái mỏng, ướp với 1 thìa tỏi băm, 1 thìa dầu hào, tiêu trong 10 phút.' },
      { stepNumber: 2, instruction: 'Hành tây bóc vỏ, bổ múi cau. Tỏi đập dập băm nhỏ.' },
      { stepNumber: 3, instruction: 'Bật lửa lớn, phi thơm tỏi rồi cho thịt bò vào xào nhanh 1-2 phút cho tái chín rồi trút ra đĩa.' },
      { stepNumber: 4, instruction: 'Dùng lại chảo, xào hành tây vừa chín tới, đổ thịt bò vào đảo nhanh tay 30 giây rồi tắt bếp.' },
    ],
  },
  {
    title: 'Đậu Hũ Chiên Giòn Nồi Chiên Không Dầu',
    description: 'Bên ngoài giòn rụm vàng ươm, bên trong mềm mọng không hề ngấy dầu mỡ.',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800',
    prepTimeMinutes: 5,
    cookTimeMinutes: 15,
    servings: 2,
    difficulty: 'EASY',
    appliance: 'AIRFRYER',
    ingredients: [
      { name: 'Đậu phụ', normalized_name: 'dau phu', quantity: '3', unit: 'miếng', isOptional: false },
      { name: 'Hành lá', normalized_name: 'hanh la', quantity: '2', unit: 'nhánh', isOptional: true },
      { name: 'Nước mắm', normalized_name: 'nuoc mam', quantity: '1', unit: 'muỗng canh', isOptional: true },
      { name: 'Ớt', normalized_name: 'ot', quantity: '1', unit: 'quả', isOptional: true },
    ],
    ingredientKeywords: ['đậu phụ', 'đậu hũ', 'hành lá', 'nước mắm', 'ớt'],
    instructions: [
      { stepNumber: 1, instruction: 'Đậu phụ thấm khô nước bằng khăn giấy, cắt miếng vuông vừa ăn.' },
      { stepNumber: 2, instruction: 'Quét 1 lớp dầu ăn mỏng quanh từng miếng đậu, xếp vào giỏ nồi chiên không dầu.' },
      { stepNumber: 3, instruction: 'Nướng ở 190°C trong 12 phút, sau đó lật mặt nướng thêm 5 phút ở 200°C cho giòn rụm.' },
      { stepNumber: 4, instruction: 'Pha nước mắm tỏi ớt hành hoa để chấm kèm khi còn nóng hổi.' },
    ],
  },
  {
    title: 'Sườn Heo Nướng Mật Ong Nồi Chiên',
    description: 'Sườn nướng vàng óng, thịt mềm mọng thấm đẫm gia vị mật ong và tỏi băm.',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=800',
    prepTimeMinutes: 10,
    cookTimeMinutes: 20,
    servings: 3,
    difficulty: 'MEDIUM',
    appliance: 'AIRFRYER',
    ingredients: [
      { name: 'Sườn heo', normalized_name: 'suon heo', quantity: '400', unit: 'gram', isOptional: false },
      { name: 'Tỏi', normalized_name: 'toi', quantity: '3', unit: 'tép', isOptional: false },
      { name: 'Hành tím', normalized_name: 'hanh tim', quantity: '2', unit: 'củ', isOptional: true },
      { name: 'Dầu hào', normalized_name: 'dau hao', quantity: '1', unit: 'muỗng canh', isOptional: true },
      { name: 'Nước mắm', normalized_name: 'nuoc mam', quantity: '1', unit: 'muỗng canh', isOptional: true },
    ],
    ingredientKeywords: ['sườn heo', 'sườn', 'thịt heo', 'tỏi', 'hành tím', 'dầu hào', 'nước mắm'],
    instructions: [
      { stepNumber: 1, instruction: 'Sườn chặt khúc, chần qua nước sôi rồi ướp với tỏi băm, hành tím, dầu hào, nước mắm trong 20 phút.' },
      { stepNumber: 2, instruction: 'Làm nóng nồi chiên không dầu ở 180°C trong 3 phút.' },
      { stepNumber: 3, instruction: 'Xếp sườn vào nướng 180°C trong 12 phút. Lật mặt sườn quét thêm nước sốt ướp.' },
      { stepNumber: 4, instruction: 'Nướng tiếp 8 phút ở 190°C cho sườn chín vàng thơm lừng.' },
    ],
  },
  {
    title: 'Cơm Gà Nấm Bằng Nồi Cơm Điện',
    description: 'Món cơm lười 1 nồi: gạo dẻo thơm ngấm vị ngọt của gà và nấm hương thanh mát.',
    imageUrl: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?q=80&w=800',
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    servings: 2,
    difficulty: 'EASY',
    appliance: 'RICE_COOKER',
    ingredients: [
      { name: 'Gạo', normalized_name: 'gao', quantity: '1.5', unit: 'lon', isOptional: false },
      { name: 'Thịt gà', normalized_name: 'thit ga', quantity: '200', unit: 'gram', isOptional: false },
      { name: 'Nấm', normalized_name: 'nam', quantity: '80', unit: 'gram', isOptional: false },
      { name: 'Cà rốt', normalized_name: 'ca rot', quantity: '1/2', unit: 'củ', isOptional: true },
      { name: 'Gừng', normalized_name: 'gung', quantity: '1', unit: 'nhánh', isOptional: true },
      { name: 'Hành lá', normalized_name: 'hanh la', quantity: '2', unit: 'nhánh', isOptional: true },
    ],
    ingredientKeywords: ['gạo', 'thịt gà', 'ức gà', 'đùi gà', 'nấm', 'cà rốt', 'gừng', 'hành lá'],
    instructions: [
      { stepNumber: 1, instruction: 'Gà cắt miếng vừa ăn, ướp với chút hạt nêm, tiêu, gừng băm và dầu hào 10 phút.' },
      { stepNumber: 2, instruction: 'Vo gạo sạch cho vào nồi cơm điện, đong lượng nước vừa đủ như nấu cơm bình thường.' },
      { stepNumber: 3, instruction: 'Xếp thịt gà, nấm và cà rốt thái hạt lựu lên trên mặt gạo. Đậy nắp bấm nút Cook.' },
      { stepNumber: 4, instruction: 'Khi nồi bật nút Warm, mở nắp rắc hành lá cắt nhỏ, xới đều và thưởng thức ngay.' },
    ],
  },
  {
    title: 'Canh Kim Chi Đậu Phụ Thịt Heo',
    description: 'Nước canh cay ấm nồng, kim chi giòn chua và đậu hũ mềm tan cho ngày se lạnh.',
    imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?q=80&w=800',
    prepTimeMinutes: 5,
    cookTimeMinutes: 12,
    servings: 3,
    difficulty: 'EASY',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Kim chi', normalized_name: 'kim chi', quantity: '150', unit: 'gram', isOptional: false },
      { name: 'Thịt heo', normalized_name: 'thit heo', quantity: '150', unit: 'gram', isOptional: false },
      { name: 'Đậu phụ', normalized_name: 'dau phu', quantity: '2', unit: 'miếng', isOptional: false },
      { name: 'Hành lá', normalized_name: 'hanh la', quantity: '2', unit: 'nhánh', isOptional: true },
      { name: 'Tỏi', normalized_name: 'toi', quantity: '2', unit: 'tép', isOptional: true },
    ],
    ingredientKeywords: ['kim chi', 'thịt heo', 'thịt ba chỉ', 'đậu phụ', 'đậu hũ', 'hành lá', 'tỏi'],
    instructions: [
      { stepNumber: 1, instruction: 'Thịt heo cắt lát mỏng. Kim chi cắt khúc vừa ăn. Đậu phụ cắt miếng vuông.' },
      { stepNumber: 2, instruction: 'Phi thơm tỏi băm, cho thịt heo vào xào săn, tiếp tục cho kim chi vào đảo đều 2 phút.' },
      { stepNumber: 3, instruction: 'Đổ 500ml nước lọc và 3 thìa nước cốt kim chi vào đun sôi bùng lên.' },
      { stepNumber: 4, instruction: 'Thả đậu phụ vào nấu thêm 3 phút, nêm chút hạt nêm vừa ăn, rắc hành lá rồi tắt bếp.' },
    ],
  },
  {
    title: 'Cơm Chiên Trứng Xúc Xích',
    description: 'Món vét cơm nguội siêu tốc, thơm lừng giòn hạt cho bữa ăn nhanh gọn.',
    imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?q=80&w=800',
    prepTimeMinutes: 5,
    cookTimeMinutes: 10,
    servings: 2,
    difficulty: 'EASY',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Cơm nguội', normalized_name: 'com nguoi', quantity: '2', unit: 'chén', isOptional: false },
      { name: 'Trứng gà', normalized_name: 'trung ga', quantity: '2', unit: 'quả', isOptional: false },
      { name: 'Xúc xích', normalized_name: 'xuc xich', quantity: '2', unit: 'cây', isOptional: false },
      { name: 'Hành lá', normalized_name: 'hanh la', quantity: '2', unit: 'nhánh', isOptional: false },
      { name: 'Cà rốt', normalized_name: 'ca rot', quantity: '1/2', unit: 'củ', isOptional: true },
    ],
    ingredientKeywords: ['cơm nguội', 'cơm', 'trứng', 'trứng gà', 'xúc xích', 'hành lá', 'cà rốt'],
    instructions: [
      { stepNumber: 1, instruction: 'Xúc xích và cà rốt thái hạt lựu. Hành lá cắt nhỏ.' },
      { stepNumber: 2, instruction: 'Đập 1 quả trứng trộn đều trực tiếp vào tô cơm nguội cho hạt cơm vàng óng.' },
      { stepNumber: 3, instruction: 'Phi thơm đầu hành, cho xúc xích và cà rốt vào xào săn lại rồi vớt ra.' },
      { stepNumber: 4, instruction: 'Đổ cơm vào đảo lửa lớn cho săn hạt, thêm quả trứng còn lại và xúc xích vào, nêm nước tương, rắc hành lá.' },
    ],
  },
  {
    title: 'Trứng Hấp Kiểu Hàn Lò Vi Sóng',
    description: 'Trứng hấp mềm mịn bồng bềnh, thơm béo phô mai chỉ mất 3 phút với lò vi sóng.',
    imageUrl: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?q=80&w=800',
    prepTimeMinutes: 2,
    cookTimeMinutes: 3,
    servings: 1,
    difficulty: 'EASY',
    appliance: 'MICROWAVE',
    ingredients: [
      { name: 'Trứng gà', normalized_name: 'trung ga', quantity: '2', unit: 'quả', isOptional: false },
      { name: 'Hành lá', normalized_name: 'hanh la', quantity: '1', unit: 'nhánh', isOptional: false },
      { name: 'Phô mai', normalized_name: 'pho mai', quantity: '1', unit: 'lát', isOptional: true },
      { name: 'Nước mắm', normalized_name: 'nuoc mam', quantity: '1/2', unit: 'muỗng cà phê', isOptional: true },
    ],
    ingredientKeywords: ['trứng gà', 'trứng', 'hành lá', 'phô mai', 'nước mắm'],
    instructions: [
      { stepNumber: 1, instruction: 'Đập trứng vào cốc sứ hoặc tô chịu nhiệt, thêm 50ml nước lọc, nước mắm và hành lá cắt nhỏ rồi đánh đều.' },
      { stepNumber: 2, instruction: 'Đặt 1 lát phô mai lên trên cùng, bọc màng bọc thực phẩm và chọc vài lỗ thoát hơi.' },
      { stepNumber: 3, instruction: 'Quay lò vi sóng công suất trung bình cao trong 2.5 - 3 phút đến khi trứng nở phồng mềm mịn.' },
    ],
  },
  {
    title: 'Khoai Lang Nướng Nồi Chiên Không Dầu',
    description: 'Khoai lang mật nướng ứa mật dẻo quánh, thơm lừng ngọt lịm cho bữa phụ healthy.',
    imageUrl: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?q=80&w=800',
    prepTimeMinutes: 5,
    cookTimeMinutes: 30,
    servings: 2,
    difficulty: 'EASY',
    appliance: 'AIRFRYER',
    ingredients: [
      { name: 'Khoai lang', normalized_name: 'khoai lang', quantity: '3', unit: 'củ', isOptional: false },
      { name: 'Bơ', normalized_name: 'bo', quantity: '10', unit: 'gram', isOptional: true },
    ],
    ingredientKeywords: ['khoai lang', 'bơ'],
    instructions: [
      { stepNumber: 1, instruction: 'Khoai lang rửa sạch vỏ, để ráo nước hoặc thấm khô.' },
      { stepNumber: 2, instruction: 'Xếp khoai vào nồi chiên không dầu, nướng ở 180°C trong 20 phút.' },
      { stepNumber: 3, instruction: 'Lật mặt khoai nướng tiếp ở 200°C trong 10-15 phút đến khi vỏ phồng, mật tơi chảy ra.' },
    ],
  },
  {
    title: 'Ức Gà Áp Chảo Rau Củ Eat Clean',
    description: 'Ức gà mềm ngọt không hề khô xác, ăn kèm bông cải và ớt chuông thanh đạm.',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800',
    prepTimeMinutes: 10,
    cookTimeMinutes: 10,
    servings: 1,
    difficulty: 'EASY',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Thịt gà', normalized_name: 'thit ga', quantity: '200', unit: 'gram', isOptional: false },
      { name: 'Bông cải', normalized_name: 'bong cai', quantity: '100', unit: 'gram', isOptional: false },
      { name: 'Ớt chuông', normalized_name: 'ot chuong', quantity: '1/2', unit: 'quả', isOptional: true },
      { name: 'Tỏi', normalized_name: 'toi', quantity: '2', unit: 'tép', isOptional: true },
      { name: 'Tiêu', normalized_name: 'tieu', quantity: '1/2', unit: 'muỗng cà phê', isOptional: true },
    ],
    ingredientKeywords: ['thịt gà', 'ức gà', 'bông cải', 'súp lơ', 'ớt chuông', 'tỏi', 'tiêu'],
    instructions: [
      { stepNumber: 1, instruction: 'Ức gà khía nhẹ mặt, ướp với chút muối, tiêu và tỏi băm 10 phút.' },
      { stepNumber: 2, instruction: 'Bông cải và ớt chuông chần sơ qua nước sôi 1 phút rồi vớt ra ngâm nước lạnh.' },
      { stepNumber: 3, instruction: 'Quét 1 lớp dầu ô liu lên chảo, áp chảo ức gà mỗi mặt 4-5 phút trên lửa vừa cho chín vàng thơm.' },
      { stepNumber: 4, instruction: 'Cho bông cải và ớt chuông vào đảo nhanh 1 phút rồi bày ra đĩa ăn kèm sốt mè rang.' },
    ],
  },
  {
    title: 'Canh Trứng Cà Chua (Canh Mây)',
    description: 'Bát canh ngọt mát, nhẹ bụng chỉ mất 5 phút nấu từ trứng và cà chua.',
    imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?q=80&w=800',
    prepTimeMinutes: 3,
    cookTimeMinutes: 5,
    servings: 3,
    difficulty: 'EASY',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Trứng gà', normalized_name: 'trung ga', quantity: '2', unit: 'quả', isOptional: false },
      { name: 'Cà chua', normalized_name: 'ca chua', quantity: '2', unit: 'quả', isOptional: false },
      { name: 'Hành lá', normalized_name: 'hanh la', quantity: '2', unit: 'nhánh', isOptional: false },
      { name: 'Hành tím', normalized_name: 'hanh tim', quantity: '1', unit: 'củ', isOptional: true },
    ],
    ingredientKeywords: ['trứng', 'trứng gà', 'cà chua', 'hành lá', 'hành tím'],
    instructions: [
      { stepNumber: 1, instruction: 'Cà chua rửa sạch cắt múi cau. Trứng đánh tan trong chén.' },
      { stepNumber: 2, instruction: 'Phi thơm hành tím, cho cà chua vào xào mềm tạo màu đỏ đẹp mắt.' },
      { stepNumber: 3, instruction: 'Đổ 500ml nước vào đun sôi, nêm 1 thìa hạt nêm và nước mắm vừa ăn.' },
      { stepNumber: 4, instruction: 'Hạ lửa nhỏ, đổ từ từ trứng vào nồi đồng thời khuấy nhẹ theo 1 chiều tạo vân mây đẹp mắt, rắc hành lá tắt bếp.' },
    ],
  },
  {
    title: 'Thịt Heo Kho Tiêu Đậm Đà',
    description: 'Thịt ba chỉ thơm béo ngậy, sốt tiêu đen cay nồng ăn cùng cơm nóng tuyệt hảo.',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=800',
    prepTimeMinutes: 10,
    cookTimeMinutes: 20,
    servings: 3,
    difficulty: 'MEDIUM',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Thịt heo', normalized_name: 'thit heo', quantity: '350', unit: 'gram', isOptional: false },
      { name: 'Hành tím', normalized_name: 'hanh tim', quantity: '2', unit: 'củ', isOptional: false },
      { name: 'Tỏi', normalized_name: 'toi', quantity: '3', unit: 'tép', isOptional: false },
      { name: 'Hành lá', normalized_name: 'hanh la', quantity: '2', unit: 'nhánh', isOptional: true },
      { name: 'Tiêu', normalized_name: 'tieu', quantity: '1', unit: 'muỗng canh', isOptional: true },
      { name: 'Ớt', normalized_name: 'ot', quantity: '1', unit: 'quả', isOptional: true },
    ],
    ingredientKeywords: ['thịt heo', 'thịt lợn', 'thịt ba chỉ', 'hành tím', 'tỏi', 'hành lá', 'tiêu', 'ớt'],
    instructions: [
      { stepNumber: 1, instruction: 'Thịt heo rửa sạch, cắt miếng con chì vừa ăn. Ướp với hành tỏi băm, nước mắm, đường, tiêu 15 phút.' },
      { stepNumber: 2, instruction: 'Thắng 1 thìa đường với chút dầu ăn trên chảo cho đến khi có màu cánh gián đẹp mắt.' },
      { stepNumber: 3, instruction: 'Cho thịt vào đảo săn đều với lửa lớn cho ngấm màu nước hàng.' },
      { stepNumber: 4, instruction: 'Thêm chút nước xâm xấp mặt thịt, hạ nhỏ lửa đun liu riu 15 phút đến khi nước sốt keo lại, rắc nhiều tiêu và hành lá.' },
    ],
  },
  {
    title: 'Canh Rau Cải Thịt Băm',
    description: 'Bát canh rau thanh mát, ngọt nước từ thịt băm cho ngày bận rộn.',
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?q=80&w=800',
    prepTimeMinutes: 5,
    cookTimeMinutes: 8,
    servings: 3,
    difficulty: 'EASY',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Rau cải', normalized_name: 'rau cai', quantity: '1', unit: 'bó', isOptional: false },
      { name: 'Thịt băm', normalized_name: 'thit bam', quantity: '100', unit: 'gram', isOptional: false },
      { name: 'Hành tím', normalized_name: 'hanh tim', quantity: '1', unit: 'củ', isOptional: true },
      { name: 'Gừng', normalized_name: 'gung', quantity: '1', unit: 'nhánh nhỏ', isOptional: true },
    ],
    ingredientKeywords: ['rau cải', 'thịt băm', 'thịt heo', 'hành tím', 'gừng'],
    instructions: [
      { stepNumber: 1, instruction: 'Rau cải nhặt rửa sạch, cắt khúc 3cm. Gừng thái sợi nhỏ.' },
      { stepNumber: 2, instruction: 'Thịt băm ướp chút hạt nêm và hành tím băm.' },
      { stepNumber: 3, instruction: 'Xào săn thịt băm với chút dầu ăn, sau đó đổ 600ml nước vào đun sôi.' },
      { stepNumber: 4, instruction: 'Nước sôi thả rau cải và vài sợi gừng vào, đun sôi lại 2 phút là rau chín ngọt, nêm nếm vừa ăn rồi tắt bếp.' },
    ],
  },
  {
    title: 'Mì Tôm Xào Trứng Bắp Cải',
    description: 'Nâng cấp gói mì tôm quen thuộc thành đĩa mì xào giòn ngọt đậm đà siêu bắt mắt.',
    imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800',
    prepTimeMinutes: 5,
    cookTimeMinutes: 7,
    servings: 1,
    difficulty: 'EASY',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Mì tôm', normalized_name: 'mi tom', quantity: '1', unit: 'gói', isOptional: false },
      { name: 'Trứng gà', normalized_name: 'trung ga', quantity: '1', unit: 'quả', isOptional: false },
      { name: 'Bắp cải', normalized_name: 'bap cai', quantity: '100', unit: 'gram', isOptional: false },
      { name: 'Hành lá', normalized_name: 'hanh la', quantity: '1', unit: 'nhánh', isOptional: true },
      { name: 'Tỏi', normalized_name: 'toi', quantity: '1', unit: 'tép', isOptional: true },
    ],
    ingredientKeywords: ['mì tôm', 'mì gói', 'trứng', 'trứng gà', 'bắp cải', 'hành lá', 'tỏi'],
    instructions: [
      { stepNumber: 1, instruction: 'Trần sơ mì tôm qua nước sôi 1 phút cho sợi mì vừa tơi rồi vớt ra xả nước lạnh để ráo.' },
      { stepNumber: 2, instruction: 'Bắp cải thái sợi mỏng rửa sạch. Đập trứng ra chén đánh tan.' },
      { stepNumber: 3, instruction: 'Phi thơm tỏi, cho bắp cải vào xào nhanh tay, đổ trứng vào đảo đều cho bám bắp cải.' },
      { stepNumber: 4, instruction: 'Cho sợi mì vào đảo lửa lớn cùng 1/2 gói gia vị mì và chút nước tương, rắc hành lá rồi tắt bếp.' },
    ],
  },
];

module.exports = recipes;
