const recipes = [
  {
    title: 'Trứng Chiên Cà Chua',
    description: 'Món ăn quốc dân nhanh gọn, bổ dưỡng, chua ngọt đậm đà cực đưa cơm.',
    imageUrl: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?q=80&w=800',
    prepTimeMinutes: 5,
    cookTimeMinutes: 10,
    servings: 2,
    difficulty: 'EASY',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Trứng gà', normalized_name: 'trung ga', quantity: '3', unit: 'quả', isOptional: false },
      { name: 'Cà chua', normalized_name: 'ca chua', quantity: '2', unit: 'quả', isOptional: false },
      { name: 'Hành lá', normalized_name: 'hanh la', quantity: '2', unit: 'nhánh', isOptional: false },
      { name: 'Hành tím', normalized_name: 'hanh tim', quantity: '1', unit: 'củ', isOptional: true },
      { name: 'Nước mắm', normalized_name: 'nuoc mam', quantity: '1', unit: 'muỗng canh', isOptional: true },
    ],
    ingredientKeywords: ['trứng', 'trứng gà', 'cà chua', 'hành lá', 'hành tím', 'nước mắm'],
    instructions: [
      { stepNumber: 1, instruction: 'Cà chua rửa sạch, thái múi cau. Hành lá cắt nhỏ, hành tím băm nhuyễn.' },
      { stepNumber: 2, instruction: 'Đập 3 quả trứng vào tô, thêm 1/2 thìa hạt nêm, tiêu và hành lá, đánh tan đều.' },
      { stepNumber: 3, instruction: 'Phi thơm hành tím với 1 thìa dầu ăn, cho cà chua vào xào mềm cho ra nước sốt đỏ.' },
      { stepNumber: 4, instruction: 'Đổ từ từ trứng vào chảo, để lửa nhỏ, đảo nhẹ tay cho trứng đông sệt lại rồi tắt bếp.' },
    ],
  },
  {
    title: 'Đậu Hũ Sốt Cà Chua',
    description: 'Đậu hũ chiên giòn quyện cùng sốt cà chua thơm nức mùi hành hoa.',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800',
    prepTimeMinutes: 5,
    cookTimeMinutes: 12,
    servings: 2,
    difficulty: 'EASY',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Đậu phụ', normalized_name: 'dau phu', quantity: '3', unit: 'miếng', isOptional: false },
      { name: 'Cà chua', normalized_name: 'ca chua', quantity: '2', unit: 'quả', isOptional: false },
      { name: 'Hành lá', normalized_name: 'hanh la', quantity: '2', unit: 'nhánh', isOptional: false },
      { name: 'Tỏi', normalized_name: 'toi', quantity: '2', unit: 'tép', isOptional: true },
      { name: 'Nước mắm', normalized_name: 'nuoc mam', quantity: '1', unit: 'muỗng canh', isOptional: true },
    ],
    ingredientKeywords: ['đậu phụ', 'đậu hũ', 'cà chua', 'hành lá', 'tỏi', 'nước mắm'],
    instructions: [
      { stepNumber: 1, instruction: 'Đậu phụ cắt miếng vuông vừa ăn, chiên vàng giòn các mặt rồi vớt ra đĩa.' },
      { stepNumber: 2, instruction: 'Cà chua băm nhỏ. Phi thơm tỏi băm, cho cà chua vào xào nhuyễn thành sốt sệt.' },
      { stepNumber: 3, instruction: 'Nêm 1 thìa nước mắm, 1 thìa đường, chút tiêu rồi cho đậu phụ đã chiên vào đảo đều.' },
      { stepNumber: 4, instruction: 'Đun nhỏ lửa 3-5 phút cho đậu ngấm sốt, rắc hành lá cắt nhỏ lên trên rồi tắt bếp.' },
    ],
  },
  {
    title: 'Thịt Bò Xào Hành Tây',
    description: 'Thịt bò mềm ngọt, hành tây giòn ngọt hòa quyện thơm nức mùi tiêu.',
    imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?q=80&w=800',
    prepTimeMinutes: 10,
    cookTimeMinutes: 8,
    servings: 3,
    difficulty: 'EASY',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Thịt bò', normalized_name: 'thit bo', quantity: '250', unit: 'gram', isOptional: false },
      { name: 'Hành tây', normalized_name: 'hanh tay', quantity: '1', unit: 'củ', isOptional: false },
      { name: 'Tỏi', normalized_name: 'toi', quantity: '3', unit: 'tép', isOptional: false },
      { name: 'Cần tây', normalized_name: 'can tay', quantity: '2', unit: 'nhánh', isOptional: true },
      { name: 'Dầu hào', normalized_name: 'dau hao', quantity: '1', unit: 'muỗng canh', isOptional: true },
      { name: 'Tiêu', normalized_name: 'tieu', quantity: '1/2', unit: 'muỗng cà phê', isOptional: true },
    ],
    ingredientKeywords: ['thịt bò', 'hành tây', 'tỏi', 'cần tây', 'dầu hào', 'tiêu'],
    instructions: [
      { stepNumber: 1, instruction: 'Thịt bò thái mỏng, ướp với 1 thìa tỏi băm, 1 thìa dầu hào, tiêu trong 10 phút.' },
      { stepNumber: 2, instruction: 'Hành tây bóc vỏ, bổ múi cau. Tỏi đập dập băm nhỏ.' },
      { stepNumber: 3, instruction: 'Bật lửa lớn, phi thơm tỏi rồi cho thịt bò vào xào nhanh 1-2 phút cho tái chín rồi trút ra đĩa.' },
      { stepNumber: 4, instruction: 'Dùng lại chảo, xào hành tây vừa chín tới, đổ thịt bò vào đảo nhanh tay 30 giây rồi tắt bếp.' },
    ],
  },
  {
    title: 'Rau Muống Xào Tỏi Giòn Xanh',
    description: 'Rau muống xanh mướt, giòn sần sật dậy mùi tỏi phi thơm lừng.',
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?q=80&w=800',
    prepTimeMinutes: 5,
    cookTimeMinutes: 5,
    servings: 3,
    difficulty: 'EASY',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Rau muống', normalized_name: 'rau muong', quantity: '1', unit: 'bó', isOptional: false },
      { name: 'Tỏi', normalized_name: 'toi', quantity: '1', unit: 'củ', isOptional: false },
      { name: 'Nước mắm', normalized_name: 'nuoc mam', quantity: '1', unit: 'muỗng canh', isOptional: true },
      { name: 'Dầu hào', normalized_name: 'dau hao', quantity: '1', unit: 'muỗng cà phê', isOptional: true },
    ],
    ingredientKeywords: ['rau muống', 'tỏi', 'nước mắm', 'dầu hào'],
    instructions: [
      { stepNumber: 1, instruction: 'Rau muống nhặt khúc non, rửa sạch để ráo. Tỏi đập dập băm nhỏ.' },
      { stepNumber: 2, instruction: 'Chần sơ rau muống qua nước sôi 30 giây với chút muối rồi vớt ra ngâm nước đá cho giòn xanh.' },
      { stepNumber: 3, instruction: 'Đun nóng dầu ăn, phi thơm 2/3 lượng tỏi băm đến khi vàng thơm.' },
      { stepNumber: 4, instruction: 'Cho rau muống vào xào lửa lớn cùng nước mắm và dầu hào, rắc nốt tỏi còn lại vào đảo nhanh 1 phút rồi tắt bếp.' },
    ],
  },
  {
    title: 'Thịt Kho Trứng Nước Dừa Đậm Đà',
    description: 'Thịt ba chỉ mềm rục, trứng ngấm vị béo ngậy ngọt thơm từ nước dừa.',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=800',
    prepTimeMinutes: 15,
    cookTimeMinutes: 35,
    servings: 4,
    difficulty: 'MEDIUM',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Thịt heo', normalized_name: 'thit heo', quantity: '400', unit: 'gram', isOptional: false },
      { name: 'Trứng gà', normalized_name: 'trung ga', quantity: '4', unit: 'quả', isOptional: false },
      { name: 'Hành tím', normalized_name: 'hanh tim', quantity: '3', unit: 'củ', isOptional: false },
      { name: 'Tỏi', normalized_name: 'toi', quantity: '3', unit: 'tép', isOptional: false },
      { name: 'Nước mắm', normalized_name: 'nuoc mam', quantity: '3', unit: 'muỗng canh', isOptional: false },
      { name: 'Ớt', normalized_name: 'ot', quantity: '1', unit: 'quả', isOptional: true },
      { name: 'Tiêu', normalized_name: 'tieu', quantity: '1/2', unit: 'muỗng cà phê', isOptional: true },
    ],
    ingredientKeywords: ['thịt heo', 'thịt ba chỉ', 'trứng gà', 'trứng vịt', 'hành tím', 'tỏi', 'nước mắm', 'ớt', 'tiêu'],
    instructions: [
      { stepNumber: 1, instruction: 'Thịt heo cắt miếng vuông vừa ăn, luộc sơ 2 phút rồi ướp nước mắm, hành tỏi băm, tiêu trong 20 phút.' },
      { stepNumber: 2, instruction: 'Trứng gà luộc chín, bóc sạch vỏ.' },
      { stepNumber: 3, instruction: 'Thắng nước hàng tạo màu cánh gián, cho thịt vào xào săn đều bề mặt.' },
      { stepNumber: 4, instruction: 'Đổ nước xâm xấp mặt thịt, đun sôi rồi hạ lửa liu riu, thả trứng vào kho 30 phút đến khi thịt mềm rục.' },
    ],
  },
  {
    title: 'Cá Kho Tộ Đậm Vị',
    description: 'Cá kho keo sánh, vị mặn ngọt cay nồng của tiêu và ớt cực kỳ tốn cơm.',
    imageUrl: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?q=80&w=800',
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    servings: 3,
    difficulty: 'MEDIUM',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Cá', normalized_name: 'ca', quantity: '400', unit: 'gram', isOptional: false },
      { name: 'Hành tím', normalized_name: 'hanh tim', quantity: '3', unit: 'củ', isOptional: false },
      { name: 'Tỏi', normalized_name: 'toi', quantity: '3', unit: 'tép', isOptional: false },
      { name: 'Ớt', normalized_name: 'ot', quantity: '2', unit: 'quả', isOptional: false },
      { name: 'Nước mắm', normalized_name: 'nuoc mam', quantity: '3', unit: 'muỗng canh', isOptional: false },
      { name: 'Tiêu', normalized_name: 'tieu', quantity: '1', unit: 'muỗng canh', isOptional: false },
      { name: 'Hành lá', normalized_name: 'hanh la', quantity: '2', unit: 'nhánh', isOptional: true },
    ],
    ingredientKeywords: ['cá', 'hành tím', 'tỏi', 'ớt', 'nước mắm', 'tiêu', 'hành lá'],
    instructions: [
      { stepNumber: 1, instruction: 'Cá làm sạch, cắt khúc vừa ăn, để ráo nước. Ướp với nước mắm, hạt nêm, tiêu, hành tỏi băm 20 phút.' },
      { stepNumber: 2, instruction: 'Thắng 1.5 thìa đường với dầu ăn thành nước màu cánh gián trong nồi đất hoặc chảo sâu lòng.' },
      { stepNumber: 3, instruction: 'Xếp cá vào đun lửa vừa cho cá săn 2 mặt, đổ nước ướp cá và thêm chút nước sôi xăm xắp.' },
      { stepNumber: 4, instruction: 'Kho nhỏ lửa 20 phút đến khi nước sốt sánh kẹo, rắc thật nhiều tiêu, ớt cắt lát và hành lá.' },
    ],
  },
  {
    title: 'Tôm Rim Thịt Ba Chỉ',
    description: 'Tôm giòn ngọt quyện thịt ba chỉ bóng bẩy đậm đà, màu sắc vàng óng hấp dẫn.',
    imageUrl: 'https://images.unsplash.com/photo-1559847844-5315695dadae?q=80&w=800',
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    servings: 3,
    difficulty: 'EASY',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Tôm', normalized_name: 'tom', quantity: '200', unit: 'gram', isOptional: false },
      { name: 'Thịt heo', normalized_name: 'thit heo', quantity: '200', unit: 'gram', isOptional: false },
      { name: 'Hành tím', normalized_name: 'hanh tim', quantity: '2', unit: 'củ', isOptional: false },
      { name: 'Tỏi', normalized_name: 'toi', quantity: '2', unit: 'tép', isOptional: false },
      { name: 'Nước mắm', normalized_name: 'nuoc mam', quantity: '2', unit: 'muỗng canh', isOptional: false },
      { name: 'Hành lá', normalized_name: 'hanh la', quantity: '2', unit: 'nhánh', isOptional: true },
      { name: 'Tiêu', normalized_name: 'tieu', quantity: '1/2', unit: 'muỗng cà phê', isOptional: true },
    ],
    ingredientKeywords: ['tôm', 'thịt heo', 'thịt ba chỉ', 'hành tím', 'tỏi', 'nước mắm', 'hành lá', 'tiêu'],
    instructions: [
      { stepNumber: 1, instruction: 'Tôm rửa sạch cắt râu. Thịt heo thái con chì nhỏ.' },
      { stepNumber: 2, instruction: 'Cho thịt heo vào chảo đảo săn cháy cạnh cho ra bớt mỡ, múc bớt mỡ thừa ra chén.' },
      { stepNumber: 3, instruction: 'Phi hành tỏi băm trong chảo, cho tôm vào đảo cùng thịt với lửa lớn đến khi tôm chuyển đỏ hồng.' },
      { stepNumber: 4, instruction: 'Nêm 2 thìa nước mắm, 1 thìa đường, rim lửa nhỏ cho nước sốt keo bám đều tôm thịt, rắc hành lá và tiêu.' },
    ],
  },
  {
    title: 'Canh Bí Đỏ Thịt Băm',
    description: 'Bí đỏ bở bùi, nước canh ngọt lịm bổ dưỡng cho cả gia đình.',
    imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?q=80&w=800',
    prepTimeMinutes: 10,
    cookTimeMinutes: 12,
    servings: 3,
    difficulty: 'EASY',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Bí đỏ', normalized_name: 'bi do', quantity: '300', unit: 'gram', isOptional: false },
      { name: 'Thịt băm', normalized_name: 'thit bam', quantity: '150', unit: 'gram', isOptional: false },
      { name: 'Hành lá', normalized_name: 'hanh la', quantity: '2', unit: 'nhánh', isOptional: false },
      { name: 'Hành tím', normalized_name: 'hanh tim', quantity: '1', unit: 'củ', isOptional: true },
      { name: 'Tiêu', normalized_name: 'tieu', quantity: '1/2', unit: 'muỗng cà phê', isOptional: true },
    ],
    ingredientKeywords: ['bí đỏ', 'thịt băm', 'thịt heo', 'hành lá', 'hành tím', 'tiêu'],
    instructions: [
      { stepNumber: 1, instruction: 'Bí đỏ gọt vỏ, cắt miếng vuông vừa ăn. Thịt băm ướp chút tiêu và hạt nêm.' },
      { stepNumber: 2, instruction: 'Phi thơm hành tím với 1 thìa dầu ăn, cho thịt băm vào xào săn.' },
      { stepNumber: 3, instruction: 'Đổ 700ml nước vào đun sôi, thả bí đỏ vào nấu trong 8-10 phút cho bí chín mềm bở.' },
      { stepNumber: 4, instruction: 'Nêm lại hạt nêm, nước mắm vừa ăn, rắc hành lá cắt nhỏ rồi tắt bếp.' },
    ],
  },
  {
    title: 'Canh Khổ Qua Nhồi Thịt',
    description: 'Món canh thanh nhiệt giải độc, vị đắng dịu hòa quyện cùng nhân thịt ngọt bùi.',
    imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?q=80&w=800',
    prepTimeMinutes: 15,
    cookTimeMinutes: 20,
    servings: 3,
    difficulty: 'MEDIUM',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Khổ qua', normalized_name: 'kho qua', quantity: '2', unit: 'trái', isOptional: false },
      { name: 'Thịt băm', normalized_name: 'thit bam', quantity: '200', unit: 'gram', isOptional: false },
      { name: 'Nấm', normalized_name: 'nam', quantity: '30', unit: 'gram', isOptional: false },
      { name: 'Hành lá', normalized_name: 'hanh la', quantity: '2', unit: 'nhánh', isOptional: false },
      { name: 'Hành tím', normalized_name: 'hanh tim', quantity: '1', unit: 'củ', isOptional: true },
      { name: 'Tiêu', normalized_name: 'tieu', quantity: '1/2', unit: 'muỗng cà phê', isOptional: true },
    ],
    ingredientKeywords: ['khổ qua', 'mướp đắng', 'thịt băm', 'thịt heo', 'nấm', 'hành lá', 'hành tím', 'tiêu'],
    instructions: [
      { stepNumber: 1, instruction: 'Khổ qua cắt khúc 4cm, móc sạch ruột trắng. Nấm ngâm mềm băm nhỏ.' },
      { stepNumber: 2, instruction: 'Trộn thịt băm cùng nấm, hành tím băm, tiêu, hạt nêm rồi nhồi chặt vào lòng từng khúc khổ qua.' },
      { stepNumber: 3, instruction: 'Đun sôi 800ml nước lọc, nhẹ nhàng thả các khúc khổ qua nhồi thịt vào nấu lửa vừa.' },
      { stepNumber: 4, instruction: 'Hầm 15-20 phút cho khổ qua chín mềm, hớt bọt cho nước trong, nêm nước mắm và rắc hành lá.' },
    ],
  },
  {
    title: 'Bánh Mì Ốp La Xúc Xích Dưa Leo',
    description: 'Bữa sáng siêu năng lượng giòn rụm chỉ mất 5 phút chuẩn bị.',
    imageUrl: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?q=80&w=800',
    prepTimeMinutes: 2,
    cookTimeMinutes: 5,
    servings: 1,
    difficulty: 'EASY',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Bánh mì', normalized_name: 'banh mi', quantity: '1', unit: 'ổ', isOptional: false },
      { name: 'Trứng gà', normalized_name: 'trung ga', quantity: '2', unit: 'quả', isOptional: false },
      { name: 'Xúc xích', normalized_name: 'xuc xich', quantity: '1', unit: 'cây', isOptional: false },
      { name: 'Dưa leo', normalized_name: 'dua leo', quantity: '1/2', unit: 'trái', isOptional: true },
      { name: 'Bơ', normalized_name: 'bo', quantity: '10', unit: 'gram', isOptional: true },
    ],
    ingredientKeywords: ['bánh mì', 'trứng gà', 'trứng', 'xúc xích', 'dưa leo', 'bơ'],
    instructions: [
      { stepNumber: 1, instruction: 'Xúc xích khía vảy rồng. Dưa leo rửa sạch thái lát mỏng.' },
      { stepNumber: 2, instruction: 'Đun chảy bơ trên chảo nhỏ, thả xúc xích vào chiên vàng đều.' },
      { stepNumber: 3, instruction: 'Đập 2 quả trứng gà vào chảo ốp la lòng đào hoặc chín tùy sở thích, rắc chút tiêu lên mặt trứng.' },
      { stepNumber: 4, instruction: 'Ăn kèm bánh mì nóng giòn và dưa leo cùng tương ớt hoặc xì dầu.' },
    ],
  },
  {
    title: 'Bánh Mì Bơ Tỏi Phô Mai Nồi Chiên',
    description: 'Bánh mì nướng bơ tỏi giòn tan, phô mai kéo sợi thơm phức nức mũi.',
    imageUrl: 'https://images.unsplash.com/photo-1509722747041-616f39b57569?q=80&w=800',
    prepTimeMinutes: 5,
    cookTimeMinutes: 6,
    servings: 2,
    difficulty: 'EASY',
    appliance: 'AIRFRYER',
    ingredients: [
      { name: 'Bánh mì', normalized_name: 'banh mi', quantity: '2', unit: 'ổ', isOptional: false },
      { name: 'Bơ', normalized_name: 'bo', quantity: '30', unit: 'gram', isOptional: false },
      { name: 'Tỏi', normalized_name: 'toi', quantity: '3', unit: 'tép', isOptional: false },
      { name: 'Phô mai', normalized_name: 'pho mai', quantity: '2', unit: 'lát', isOptional: false },
      { name: 'Hành lá', normalized_name: 'hanh la', quantity: '1', unit: 'nhánh', isOptional: true },
    ],
    ingredientKeywords: ['bánh mì', 'bơ', 'tỏi', 'phô mai', 'hành lá'],
    instructions: [
      { stepNumber: 1, instruction: 'Tỏi băm nhuyễn, hành lá cắt nhỏ. Đun chảy bơ rồi trộn cùng tỏi băm và hành lá.' },
      { stepNumber: 2, instruction: 'Bánh mì cắt lát chéo dày 2cm. Quét đều hỗn hợp bơ tỏi lên mặt bánh.' },
      { stepNumber: 3, instruction: 'Xếp phô mai lên trên từng lát bánh mì.' },
      { stepNumber: 4, instruction: 'Nướng trong nồi chiên không dầu ở 170°C trong 5-6 phút cho bánh vàng giòn, phô mai tan chảy.' },
    ],
  },
  {
    title: 'Mì Cay Kim Chi Xúc Xích Phô Mai',
    description: 'Tô mì nóng hổi chua cay tê lưỡi ngập tràn topping giải tỏa cơn thèm đêm khuya.',
    imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800',
    prepTimeMinutes: 3,
    cookTimeMinutes: 5,
    servings: 1,
    difficulty: 'EASY',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Mì tôm', normalized_name: 'mi tom', quantity: '1', unit: 'gói', isOptional: false },
      { name: 'Kim chi', normalized_name: 'kim chi', quantity: '80', unit: 'gram', isOptional: false },
      { name: 'Xúc xích', normalized_name: 'xuc xich', quantity: '1', unit: 'cây', isOptional: false },
      { name: 'Trứng gà', normalized_name: 'trung ga', quantity: '1', unit: 'quả', isOptional: false },
      { name: 'Phô mai', normalized_name: 'pho mai', quantity: '1', unit: 'lát', isOptional: true },
      { name: 'Hành lá', normalized_name: 'hanh la', quantity: '1', unit: 'nhánh', isOptional: true },
    ],
    ingredientKeywords: ['mì tôm', 'kim chi', 'xúc xích', 'trứng gà', 'trứng', 'phô mai', 'hành lá'],
    instructions: [
      { stepNumber: 1, instruction: 'Xúc xích cắt lát xéo. Kim chi cắt khúc.' },
      { stepNumber: 2, instruction: 'Đun sôi 400ml nước cùng kim chi và gói gia vị mì trong 2 phút.' },
      { stepNumber: 3, instruction: 'Thả vắt mì, xúc xích và đập 1 quả trứng gà vào nồi đun sôi thêm 2 phút.' },
      { stepNumber: 4, instruction: 'Tắt bếp, đặt lát phô mai và rắc hành lá lên trên, thưởng thức ngay khi phô mai chảy béo ngậy.' },
    ],
  },
  {
    title: 'Bún Xào Thịt Bò Rau Cải',
    description: 'Sợi bún dai mềm ngấm sốt bò đậm đà cùng rau cải ngọt lịm tươi mát.',
    imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800',
    prepTimeMinutes: 8,
    cookTimeMinutes: 7,
    servings: 2,
    difficulty: 'EASY',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Bún tươi', normalized_name: 'bun tuoi', quantity: '300', unit: 'gram', isOptional: false },
      { name: 'Thịt bò', normalized_name: 'thit bo', quantity: '150', unit: 'gram', isOptional: false },
      { name: 'Rau cải', normalized_name: 'rau cai', quantity: '150', unit: 'gram', isOptional: false },
      { name: 'Tỏi', normalized_name: 'toi', quantity: '3', unit: 'tép', isOptional: false },
      { name: 'Dầu hào', normalized_name: 'dau hao', quantity: '1', unit: 'muỗng canh', isOptional: true },
      { name: 'Nước tương', normalized_name: 'nuoc tuong', quantity: '1', unit: 'muỗng canh', isOptional: true },
    ],
    ingredientKeywords: ['bún tươi', 'thịt bò', 'rau cải', 'tỏi', 'dầu hào', 'nước tương'],
    instructions: [
      { stepNumber: 1, instruction: 'Thịt bò thái mỏng ướp tỏi băm, dầu hào, tiêu 10 phút. Rau cải cắt khúc.' },
      { stepNumber: 2, instruction: 'Xào nhanh thịt bò trên lửa lớn trong 1 phút vừa chín tới rồi trút ra đĩa.' },
      { stepNumber: 3, instruction: 'Phi thơm tỏi, cho rau cải và bún tươi vào xào đều với 1 thìa nước tương.' },
      { stepNumber: 4, instruction: 'Trút thịt bò vào đảo nhanh tay 30 giây rồi tắt bếp, rắc chút tiêu thơm nức.' },
    ],
  },
  {
    title: 'Miến Xào Tôm Nấm Thập Cẩm',
    description: 'Sợi miến dai trong bóng mượt, tôm giòn sần sật quyện vị ngọt tự nhiên của nấm và cà rốt.',
    imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800',
    prepTimeMinutes: 10,
    cookTimeMinutes: 10,
    servings: 2,
    difficulty: 'EASY',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Miến', normalized_name: 'mien', quantity: '150', unit: 'gram', isOptional: false },
      { name: 'Tôm', normalized_name: 'tom', quantity: '150', unit: 'gram', isOptional: false },
      { name: 'Nấm', normalized_name: 'nam', quantity: '80', unit: 'gram', isOptional: false },
      { name: 'Cà rốt', normalized_name: 'ca rot', quantity: '1/2', unit: 'củ', isOptional: true },
      { name: 'Hành lá', normalized_name: 'hanh la', quantity: '2', unit: 'nhánh', isOptional: true },
      { name: 'Tỏi', normalized_name: 'toi', quantity: '2', unit: 'tép', isOptional: true },
    ],
    ingredientKeywords: ['miến', 'tôm', 'nấm', 'cà rốt', 'hành lá', 'tỏi'],
    instructions: [
      { stepNumber: 1, instruction: 'Miến ngâm nước ấm 5 phút cho mềm rồi cắt khúc, trộn với 1 thìa dầu ăn cho không dính.' },
      { stepNumber: 2, instruction: 'Tôm bóc vỏ bỏ chỉ đen. Cà rốt thái sợi. Nấm cắt lát.' },
      { stepNumber: 3, instruction: 'Phi tỏi thơm, xào chín tôm rồi cho nấm và cà rốt vào đảo chín tới.' },
      { stepNumber: 4, instruction: 'Cho miến vào đảo đều trên lửa vừa cùng 2 thìa xì dầu và dầu hào trong 3 phút, rắc hành lá tắt bếp.' },
    ],
  },
  {
    title: 'Salad Ức Gà Trứng Luộc Eat Clean',
    description: 'Bữa ăn nhẹ giàu protein, thanh mát giòn giã giúp duy trì vóc dáng lý tưởng.',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800',
    prepTimeMinutes: 8,
    cookTimeMinutes: 8,
    servings: 1,
    difficulty: 'EASY',
    appliance: 'ALL',
    ingredients: [
      { name: 'Thịt gà', normalized_name: 'thit ga', quantity: '150', unit: 'gram', isOptional: false },
      { name: 'Trứng gà', normalized_name: 'trung ga', quantity: '1', unit: 'quả', isOptional: false },
      { name: 'Dưa leo', normalized_name: 'dua leo', quantity: '1', unit: 'trái', isOptional: false },
      { name: 'Cà chua', normalized_name: 'ca chua', quantity: '1', unit: 'quả', isOptional: false },
      { name: 'Ớt chuông', normalized_name: 'ot chuong', quantity: '1/2', unit: 'quả', isOptional: true },
    ],
    ingredientKeywords: ['thịt gà', 'ức gà', 'trứng gà', 'dưa leo', 'cà chua', 'ớt chuông'],
    instructions: [
      { stepNumber: 1, instruction: 'Ức gà luộc hoặc áp chảo chín tới rồi xé sợi. Trứng gà luộc chín cắt múi cau.' },
      { stepNumber: 2, instruction: 'Dưa leo, cà chua, ớt chuông rửa sạch cắt lát vừa ăn.' },
      { stepNumber: 3, instruction: 'Bày rau củ ra đĩa, xếp ức gà xé và trứng luộc lên trên.' },
      { stepNumber: 4, instruction: 'Rưới sốt mè rang hoặc sốt chanh mật ong lên trên và thưởng thức ngay.' },
    ],
  },
  {
    title: 'Bắp Cải Cuộn Thịt Hấp Ngọt Nước',
    description: 'Vị ngọt tự nhiên của bắp cải quyện nhân thịt băm nấm thơm bùi, ăn thanh mát không dầu mỡ.',
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?q=80&w=800',
    prepTimeMinutes: 15,
    cookTimeMinutes: 15,
    servings: 3,
    difficulty: 'MEDIUM',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Bắp cải', normalized_name: 'bap cai', quantity: '6', unit: 'lá lớn', isOptional: false },
      { name: 'Thịt băm', normalized_name: 'thit bam', quantity: '200', unit: 'gram', isOptional: false },
      { name: 'Nấm', normalized_name: 'nam', quantity: '30', unit: 'gram', isOptional: false },
      { name: 'Cà rốt', normalized_name: 'ca rot', quantity: '1/3', unit: 'củ', isOptional: true },
      { name: 'Hành lá', normalized_name: 'hanh la', quantity: '6', unit: 'cọng', isOptional: false },
      { name: 'Tiêu', normalized_name: 'tieu', quantity: '1/2', unit: 'muỗng cà phê', isOptional: true },
    ],
    ingredientKeywords: ['bắp cải', 'thịt băm', 'thịt heo', 'nấm', 'cà rốt', 'hành lá', 'tiêu'],
    instructions: [
      { stepNumber: 1, instruction: 'Lá bắp cải và cọng hành lá chần sơ qua nước sôi 1 phút cho mềm dai dễ cuộn.' },
      { stepNumber: 2, instruction: 'Thịt băm trộn cùng nấm băm, cà rốt hạt lựu, tiêu và hạt nêm.' },
      { stepNumber: 3, instruction: 'Múc nhân thịt vào lá bắp cải, cuộn chặt lại như chả giò và dùng cọng hành buộc nhẹ.' },
      { stepNumber: 4, instruction: 'Xếp vào xửng hấp trong 15 phút đến khi chín tới, chấm kèm nước tương tỏi ớt.' },
    ],
  },
  {
    title: 'Canh Rong Biển Đậu Hũ Non Thịt Băm',
    description: 'Bát canh thanh mát chuẩn vị Hàn, giải nhiệt cơ thể cực kỳ hiệu quả.',
    imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?q=80&w=800',
    prepTimeMinutes: 5,
    cookTimeMinutes: 8,
    servings: 3,
    difficulty: 'EASY',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Rong biển', normalized_name: 'rong bien', quantity: '20', unit: 'gram', isOptional: false },
      { name: 'Đậu phụ', normalized_name: 'dau phu', quantity: '1', unit: 'hộp', isOptional: false },
      { name: 'Thịt băm', normalized_name: 'thit bam', quantity: '100', unit: 'gram', isOptional: false },
      { name: 'Gừng', normalized_name: 'gung', quantity: '1', unit: 'nhánh nhỏ', isOptional: true },
      { name: 'Tỏi', normalized_name: 'toi', quantity: '2', unit: 'tép', isOptional: true },
    ],
    ingredientKeywords: ['rong biển', 'đậu phụ', 'đậu hũ', 'thịt băm', 'thịt heo', 'gừng', 'tỏi'],
    instructions: [
      { stepNumber: 1, instruction: 'Rong biển ngâm nước 5 phút cho nở mềm rồi cắt khúc. Đậu hũ non cắt miếng vuông.' },
      { stepNumber: 2, instruction: 'Phi thơm tỏi và vài sợi gừng, cho thịt băm vào xào săn.' },
      { stepNumber: 3, instruction: 'Cho rong biển vào đảo cùng thịt 1 phút, đổ 600ml nước vào đun sôi bùng.' },
      { stepNumber: 4, instruction: 'Thả đậu hũ non vào nấu 2 phút, nêm hạt nêm và vài giọt dầu mè rồi tắt bếp.' },
    ],
  },
  {
    title: 'Nấm Kho Tiêu Xì Dầu Chay Đậm Vị',
    description: 'Nấm đùi gà dai giòn, ngấm nước sốt tiêu đen mặn ngọt cay tê ăn cùng cơm trắng cực đỉnh.',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800',
    prepTimeMinutes: 5,
    cookTimeMinutes: 10,
    servings: 2,
    difficulty: 'EASY',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Nấm', normalized_name: 'nam', quantity: '300', unit: 'gram', isOptional: false },
      { name: 'Tỏi', normalized_name: 'toi', quantity: '2', unit: 'tép', isOptional: true },
      { name: 'Hành lá', normalized_name: 'hanh la', quantity: '2', unit: 'nhánh', isOptional: true },
      { name: 'Nước tương', normalized_name: 'nuoc tuong', quantity: '2', unit: 'muỗng canh', isOptional: false },
      { name: 'Tiêu', normalized_name: 'tieu', quantity: '1', unit: 'muỗng canh', isOptional: false },
      { name: 'Ớt', normalized_name: 'ot', quantity: '1', unit: 'quả', isOptional: true },
    ],
    ingredientKeywords: ['nấm', 'nấm đùi gà', 'nấm rơm', 'tỏi', 'hành lá', 'nước tương', 'tiêu', 'ớt'],
    instructions: [
      { stepNumber: 1, instruction: 'Nấm rửa sạch, cắt khoanh tròn hoặc chẻ đôi vừa ăn.' },
      { stepNumber: 2, instruction: 'Phi thơm tỏi băm, cho nấm vào đảo đều lửa vừa trong 2 phút.' },
      { stepNumber: 3, instruction: 'Pha hỗn hợp 2 thìa xì dầu, 1 thìa đường, 1/2 chén nước lọc đổ vào chảo nấm.' },
      { stepNumber: 4, instruction: 'Kho nhỏ lửa đến khi nước sốt keo bám bóng nấm, rắc thật nhiều tiêu và hành lá.' },
    ],
  },
  {
    title: 'Đậu Hũ Chiên Sả Ớt Giòn Cay',
    description: 'Lớp vỏ đậu vàng giòn rụm bám sả ớt thơm cay bùng nổ vị giác.',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800',
    prepTimeMinutes: 8,
    cookTimeMinutes: 10,
    servings: 2,
    difficulty: 'EASY',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Đậu phụ', normalized_name: 'dau phu', quantity: '3', unit: 'miếng', isOptional: false },
      { name: 'Sả', normalized_name: 'sa', quantity: '2', unit: 'cây', isOptional: false },
      { name: 'Ớt', normalized_name: 'ot', quantity: '1', unit: 'quả', isOptional: false },
      { name: 'Tỏi', normalized_name: 'toi', quantity: '2', unit: 'tép', isOptional: true },
      { name: 'Nước tương', normalized_name: 'nuoc tuong', quantity: '1', unit: 'muỗng canh', isOptional: true },
    ],
    ingredientKeywords: ['đậu phụ', 'đậu hũ', 'sả', 'ớt', 'tỏi', 'nước tương'],
    instructions: [
      { stepNumber: 1, instruction: 'Đậu hũ cắt miếng vuông khía nhẹ trên mặt. Sả, tỏi, ớt băm nhuyễn.' },
      { stepNumber: 2, instruction: 'Chiên đậu hũ trong chảo dầu nóng đến khi vàng giòn các mặt rồi vớt ra.' },
      { stepNumber: 3, instruction: 'Dùng chảo phi vàng giòn hỗn hợp sả, tỏi, ớt với chút hạt nêm và đường.' },
      { stepNumber: 4, instruction: 'Đổ đậu hũ đã chiên vào chảo đảo đều cho sả ớt bám đều mặt đậu rồi tắt bếp.' },
    ],
  },
  {
    title: 'Rau Củ Xào Thập Cẩm Bổ Dưỡng',
    description: 'Đĩa rau củ đa sắc màu tươi giòn sần sật, thanh đạm và giàu vitamin.',
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?q=80&w=800',
    prepTimeMinutes: 8,
    cookTimeMinutes: 6,
    servings: 3,
    difficulty: 'EASY',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Bông cải', normalized_name: 'bong cai', quantity: '100', unit: 'gram', isOptional: false },
      { name: 'Cà rốt', normalized_name: 'ca rot', quantity: '1/2', unit: 'củ', isOptional: false },
      { name: 'Nấm', normalized_name: 'nam', quantity: '50', unit: 'gram', isOptional: false },
      { name: 'Bắp hạt', normalized_name: 'bap hat', quantity: '50', unit: 'gram', isOptional: true },
      { name: 'Tỏi', normalized_name: 'toi', quantity: '2', unit: 'tép', isOptional: false },
      { name: 'Dầu hào', normalized_name: 'dau hao', quantity: '1', unit: 'muỗng canh', isOptional: true },
    ],
    ingredientKeywords: ['bông cải', 'cà rốt', 'nấm', 'bắp hạt', 'tỏi', 'dầu hào'],
    instructions: [
      { stepNumber: 1, instruction: 'Bông cải tách nhánh nhỏ. Cà rốt tỉa hoa thái mỏng. Nấm cắt lát.' },
      { stepNumber: 2, instruction: 'Chần sơ bông cải và cà rốt qua nước sôi 1 phút rồi vớt ra ngâm nước lạnh.' },
      { stepNumber: 3, instruction: 'Phi thơm tỏi băm, cho nấm và bắp hạt vào xào săn.' },
      { stepNumber: 4, instruction: 'Đổ bông cải và cà rốt vào đảo lửa lớn cùng 1 thìa dầu hào trong 2 phút rồi bày ra đĩa.' },
    ],
  },
  {
    title: 'Gà Nướng Sả Ớt Nồi Chiên Không Dầu',
    description: 'Thịt gà da giòn rụm bên ngoài, thịt mềm ngọt mọng nước bên trong đượm vị sả ớt.',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=800',
    prepTimeMinutes: 10,
    cookTimeMinutes: 20,
    servings: 3,
    difficulty: 'EASY',
    appliance: 'AIRFRYER',
    ingredients: [
      { name: 'Thịt gà', normalized_name: 'thit ga', quantity: '400', unit: 'gram', isOptional: false },
      { name: 'Sả', normalized_name: 'sa', quantity: '2', unit: 'cây', isOptional: false },
      { name: 'Tỏi', normalized_name: 'toi', quantity: '3', unit: 'tép', isOptional: false },
      { name: 'Ớt', normalized_name: 'ot', quantity: '1', unit: 'quả', isOptional: true },
      { name: 'Dầu hào', normalized_name: 'dau hao', quantity: '1', unit: 'muỗng canh', isOptional: false },
      { name: 'Nước mắm', normalized_name: 'nuoc mam', quantity: '1', unit: 'muỗng canh', isOptional: false },
    ],
    ingredientKeywords: ['thịt gà', 'đùi gà', 'cánh gà', 'sả', 'tỏi', 'ớt', 'dầu hào', 'nước mắm'],
    instructions: [
      { stepNumber: 1, instruction: 'Thịt gà rửa sạch, khía nhẹ mặt da. Ướp với sả tỏi ớt băm, dầu hào, nước mắm trong 20 phút.' },
      { stepNumber: 2, instruction: 'Làm nóng nồi chiên không dầu ở 180°C trong 3 phút.' },
      { stepNumber: 3, instruction: 'Xếp gà vào nướng 180°C trong 15 phút, sau đó lật mặt quét thêm nước sốt ướp.' },
      { stepNumber: 4, instruction: 'Nướng tiếp ở 200°C trong 5 phút cho lớp da vàng giòn rụm tỏa hương thơm nức.' },
    ],
  },
  {
    title: 'Bắp Nướng Mỡ Hành Nồi Chiên Không Dầu',
    description: 'Bắp ngọt lịm xém cạnh, rưới ngập mỡ hành béo ngậy chuẩn vị ăn vặt đường phố.',
    imageUrl: 'https://images.unsplash.com/photo-1551782450-a2132b4ba21d?q=80&w=800',
    prepTimeMinutes: 5,
    cookTimeMinutes: 12,
    servings: 2,
    difficulty: 'EASY',
    appliance: 'AIRFRYER',
    ingredients: [
      { name: 'Bắp hạt', normalized_name: 'bap hat', quantity: '2', unit: 'trái', isOptional: false },
      { name: 'Hành lá', normalized_name: 'hanh la', quantity: '3', unit: 'nhánh', isOptional: false },
      { name: 'Bơ', normalized_name: 'bo', quantity: '20', unit: 'gram', isOptional: false },
    ],
    ingredientKeywords: ['bắp hạt', 'bắp ngô', 'ngô', 'hành lá', 'bơ'],
    instructions: [
      { stepNumber: 1, instruction: 'Bắp bóc vỏ, quét 1 lớp bơ mỏng quanh thân bắp.' },
      { stepNumber: 2, instruction: 'Cho bắp vào nồi chiên không dầu nướng 190°C trong 12 phút đến khi hạt bắp xém vàng thơm.' },
      { stepNumber: 3, instruction: 'Hành lá cắt nhỏ, đun nóng dầu ăn hoặc bơ rồi đổ trực tiếp vào chén hành làm mỡ hành.' },
      { stepNumber: 4, instruction: 'Quét đẫm mỡ hành lên thân bắp nóng hổi và thưởng thức ngay.' },
    ],
  },
  {
    title: 'Chả Giò Chiên Giòn Rụm Nồi Chiên',
    description: 'Vỏ chả giò giòn tan vàng ươm không hề đọng dầu mỡ ngấy bụng.',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800',
    prepTimeMinutes: 2,
    cookTimeMinutes: 15,
    servings: 3,
    difficulty: 'EASY',
    appliance: 'AIRFRYER',
    ingredients: [
      { name: 'Chả giò', normalized_name: 'cha gio', quantity: '8', unit: 'cuốn', isOptional: false },
      { name: 'Dưa leo', normalized_name: 'dua leo', quantity: '1', unit: 'trái', isOptional: true },
      { name: 'Nước mắm', normalized_name: 'nuoc mam', quantity: '2', unit: 'muỗng canh', isOptional: true },
    ],
    ingredientKeywords: ['chả giò', 'nem rán', 'dưa leo', 'nước mắm'],
    instructions: [
      { stepNumber: 1, instruction: 'Lấy chả giò cấp đông ra, quét một lớp dầu ăn mỏng quanh từng cuốn chả giò.' },
      { stepNumber: 2, instruction: 'Xếp chả giò vào giỏ nồi chiên không dầu cách đều nhau.' },
      { stepNumber: 3, instruction: 'Nướng ở 180°C trong 10 phút, lật mặt nướng tiếp ở 200°C trong 5 phút cho giòn rụm.' },
      { stepNumber: 4, instruction: 'Ăn kèm dưa leo, rau sống và nước mắm chua ngọt.' },
    ],
  },
  {
    title: 'Xôi Gà Nấm Dẻo Thơm Nồi Cơm Điện',
    description: 'Hạt nếp dẻo quánh ngấm vị ngọt đậm đà từ gà và nấm hương chỉ với 1 nút bấm.',
    imageUrl: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?q=80&w=800',
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    servings: 3,
    difficulty: 'EASY',
    appliance: 'RICE_COOKER',
    ingredients: [
      { name: 'Gạo', normalized_name: 'gao', quantity: '2', unit: 'lon', isOptional: false },
      { name: 'Thịt gà', normalized_name: 'thit ga', quantity: '250', unit: 'gram', isOptional: false },
      { name: 'Nấm', normalized_name: 'nam', quantity: '80', unit: 'gram', isOptional: false },
      { name: 'Hành tím', normalized_name: 'hanh tim', quantity: '3', unit: 'củ', isOptional: false },
      { name: 'Nước tương', normalized_name: 'nuoc tuong', quantity: '1', unit: 'muỗng canh', isOptional: true },
      { name: 'Dầu hào', normalized_name: 'dau hao', quantity: '1', unit: 'muỗng canh', isOptional: true },
    ],
    ingredientKeywords: ['gạo', 'gạo nếp', 'thịt gà', 'nấm', 'hành tím', 'nước tương', 'dầu hào'],
    instructions: [
      { stepNumber: 1, instruction: 'Gạo vo sạch để ráo. Thịt gà cắt miếng vừa ăn ướp dầu hào, nước tương, tiêu.' },
      { stepNumber: 2, instruction: 'Phi thơm hành tím lát mỏng cho vàng giòn làm hành phi rồi vớt ra.' },
      { stepNumber: 3, instruction: 'Xào sơ thịt gà và nấm với phần dầu hành phi cho săn.' },
      { stepNumber: 4, instruction: 'Cho gạo vào nồi cơm điện, đong nước vừa mặt gạo, xếp thịt gà và nấm lên trên rồi bấm nút Cook. Khi chín rắc hành phi.' },
    ],
  },
  {
    title: 'Cơm Chiên Kim Chi Phô Mai Lò Vi Sóng',
    description: 'Cơm chiên kim chi chua cay hòa cùng phô mai kéo sợi dẻo béo chỉ mất 4 phút quay lò vi sóng.',
    imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?q=80&w=800',
    prepTimeMinutes: 2,
    cookTimeMinutes: 4,
    servings: 1,
    difficulty: 'EASY',
    appliance: 'MICROWAVE',
    ingredients: [
      { name: 'Cơm nguội', normalized_name: 'com nguoi', quantity: '1', unit: 'chén', isOptional: false },
      { name: 'Kim chi', normalized_name: 'kim chi', quantity: '60', unit: 'gram', isOptional: false },
      { name: 'Xúc xích', normalized_name: 'xuc xich', quantity: '1', unit: 'cây', isOptional: false },
      { name: 'Phô mai', normalized_name: 'pho mai', quantity: '2', unit: 'lát', isOptional: false },
      { name: 'Hành lá', normalized_name: 'hanh la', quantity: '1', unit: 'nhánh', isOptional: true },
    ],
    ingredientKeywords: ['cơm nguội', 'kim chi', 'xúc xích', 'phô mai', 'hành lá'],
    instructions: [
      { stepNumber: 1, instruction: 'Xúc xích và kim chi cắt nhỏ, trộn đều vào tô cơm nguội cùng 1 thìa nước cốt kim chi.' },
      { stepNumber: 2, instruction: 'Bọc màng bọc thực phẩm, quay lò vi sóng trong 2 phút ở mức nhiệt trung bình cao.' },
      { stepNumber: 3, instruction: 'Lấy ra đảo đều cơm, phủ 2 lát phô mai và hành lá lên trên cùng.' },
      { stepNumber: 4, instruction: 'Quay tiếp 1.5 - 2 phút cho phô mai tan chảy kéo sợi hấp dẫn.' },
    ],
  },
  {
    title: 'Khoai Tây Chiên Bơ Tỏi Nồi Chiên Không Dầu',
    description: 'Từng cọng khoai tây vàng ươm giòn tan, phủ sốt bơ tỏi thơm lừng nức mũi.',
    imageUrl: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?q=80&w=800',
    prepTimeMinutes: 8,
    cookTimeMinutes: 18,
    servings: 2,
    difficulty: 'EASY',
    appliance: 'AIRFRYER',
    ingredients: [
      { name: 'Khoai tây', normalized_name: 'khoai tay', quantity: '3', unit: 'củ', isOptional: false },
      { name: 'Bơ', normalized_name: 'bo', quantity: '20', unit: 'gram', isOptional: false },
      { name: 'Tỏi', normalized_name: 'toi', quantity: '3', unit: 'tép', isOptional: false },
      { name: 'Tiêu', normalized_name: 'tieu', quantity: '1/2', unit: 'muỗng cà phê', isOptional: true },
    ],
    ingredientKeywords: ['khoai tây', 'bơ', 'tỏi', 'tiêu'],
    instructions: [
      { stepNumber: 1, instruction: 'Khoai tây gọt vỏ, cắt con chì dày 1cm, ngâm nước muối 15 phút rồi vớt ra thấm thật khô.' },
      { stepNumber: 2, instruction: 'Trộn khoai tây với 1 thìa dầu ăn, xếp vào nồi chiên không dầu nướng 180°C trong 12 phút.' },
      { stepNumber: 3, instruction: 'Lắc đều giỏ chiên, nướng tiếp ở 200°C trong 6 phút cho khoai vàng giòn rụm.' },
      { stepNumber: 4, instruction: 'Đun chảy bơ phi thơm tỏi băm, trút khoai tây nóng vào đảo nhanh 30 giây rồi dọn ra đĩa.' },
    ],
  },
  {
    title: 'Cá Hấp Gừng Hành Thanh Ngọt',
    description: 'Thịt cá ngọt mềm tự nhiên, khử sạch mùi tanh nhờ hương gừng sả và nước tương thơm nức.',
    imageUrl: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?q=80&w=800',
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    servings: 3,
    difficulty: 'EASY',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Cá', normalized_name: 'ca', quantity: '500', unit: 'gram', isOptional: false },
      { name: 'Gừng', normalized_name: 'gung', quantity: '1', unit: 'củ', isOptional: false },
      { name: 'Hành lá', normalized_name: 'hanh la', quantity: '4', unit: 'nhánh', isOptional: false },
      { name: 'Hành tím', normalized_name: 'hanh tim', quantity: '2', unit: 'củ', isOptional: true },
      { name: 'Nước tương', normalized_name: 'nuoc tuong', quantity: '2', unit: 'muỗng canh', isOptional: false },
      { name: 'Dầu hào', normalized_name: 'dau hao', quantity: '1', unit: 'muỗng canh', isOptional: true },
      { name: 'Tiêu', normalized_name: 'tieu', quantity: '1/2', unit: 'muỗng cà phê', isOptional: true },
    ],
    ingredientKeywords: ['cá', 'gừng', 'hành lá', 'hành tím', 'nước tương', 'dầu hào', 'tiêu'],
    instructions: [
      { stepNumber: 1, instruction: 'Cá làm sạch khía vảy rồng. Gừng thái sợi, hành lá cắt khúc dài.' },
      { stepNumber: 2, instruction: 'Nhét gừng và đầu hành vào bụng cá, ướp chút hạt nêm, tiêu và 1 thìa nước tương trong 10 phút.' },
      { stepNumber: 3, instruction: 'Đặt cá vào đĩa sâu lòng, rải đều gừng và hành tím thái lát lên mặt cá.' },
      { stepNumber: 4, instruction: 'Hấp cách thủy lửa lớn trong 15 phút. Rưới sốt nước tương dầu hào nóng và rắc hành lá lên trên.' },
    ],
  },
  {
    title: 'Đậu Hũ Chiên Giòn Nồi Chiên Không Dầu',
    description: 'Bên ngoài giòn rụm vàng ươm, bên trong mềm mọng không hề ngấy dầu mỡ.',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800',
    prepTimeMinutes: 5,
    cookTimeMinutes: 15,
    servings: 2,
    difficulty: 'EASY',
    appliance: 'AIRFRYER',
    ingredients: [
      { name: 'Đậu phụ', normalized_name: 'dau phu', quantity: '3', unit: 'miếng', isOptional: false },
      { name: 'Hành lá', normalized_name: 'hanh la', quantity: '2', unit: 'nhánh', isOptional: true },
      { name: 'Nước mắm', normalized_name: 'nuoc mam', quantity: '1', unit: 'muỗng canh', isOptional: true },
      { name: 'Ớt', normalized_name: 'ot', quantity: '1', unit: 'quả', isOptional: true },
    ],
    ingredientKeywords: ['đậu phụ', 'đậu hũ', 'hành lá', 'nước mắm', 'ớt'],
    instructions: [
      { stepNumber: 1, instruction: 'Đậu phụ thấm khô nước bằng khăn giấy, cắt miếng vuông vừa ăn.' },
      { stepNumber: 2, instruction: 'Quét 1 lớp dầu ăn mỏng quanh từng miếng đậu, xếp vào giỏ nồi chiên không dầu.' },
      { stepNumber: 3, instruction: 'Nướng ở 190°C trong 12 phút, sau đó lật mặt nướng thêm 5 phút ở 200°C cho giòn rụm.' },
      { stepNumber: 4, instruction: 'Pha nước mắm tỏi ớt hành hoa để chấm kèm khi còn nóng hổi.' },
    ],
  },
  {
    title: 'Sườn Heo Nướng Mật Ong Nồi Chiên',
    description: 'Sườn nướng vàng óng, thịt mềm mọng thấm đẫm gia vị mật ong và tỏi băm.',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=800',
    prepTimeMinutes: 10,
    cookTimeMinutes: 20,
    servings: 3,
    difficulty: 'MEDIUM',
    appliance: 'AIRFRYER',
    ingredients: [
      { name: 'Sườn heo', normalized_name: 'suon heo', quantity: '400', unit: 'gram', isOptional: false },
      { name: 'Tỏi', normalized_name: 'toi', quantity: '3', unit: 'tép', isOptional: false },
      { name: 'Hành tím', normalized_name: 'hanh tim', quantity: '2', unit: 'củ', isOptional: true },
      { name: 'Dầu hào', normalized_name: 'dau hao', quantity: '1', unit: 'muỗng canh', isOptional: true },
      { name: 'Nước mắm', normalized_name: 'nuoc mam', quantity: '1', unit: 'muỗng canh', isOptional: true },
    ],
    ingredientKeywords: ['sườn heo', 'sườn', 'thịt heo', 'tỏi', 'hành tím', 'dầu hào', 'nước mắm'],
    instructions: [
      { stepNumber: 1, instruction: 'Sườn chặt khúc, chần qua nước sôi rồi ướp với tỏi băm, hành tím, dầu hào, nước mắm trong 20 phút.' },
      { stepNumber: 2, instruction: 'Làm nóng nồi chiên không dầu ở 180°C trong 3 phút.' },
      { stepNumber: 3, instruction: 'Xếp sườn vào nướng 180°C trong 12 phút. Lật mặt sườn quét thêm nước sốt ướp.' },
      { stepNumber: 4, instruction: 'Nướng tiếp 8 phút ở 190°C cho sườn chín vàng thơm lừng.' },
    ],
  },
  {
    title: 'Cơm Gà Nấm Bằng Nồi Cơm Điện',
    description: 'Món cơm lười 1 nồi: gạo dẻo thơm ngấm vị ngọt của gà và nấm hương thanh mát.',
    imageUrl: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?q=80&w=800',
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    servings: 2,
    difficulty: 'EASY',
    appliance: 'RICE_COOKER',
    ingredients: [
      { name: 'Gạo', normalized_name: 'gao', quantity: '1.5', unit: 'lon', isOptional: false },
      { name: 'Thịt gà', normalized_name: 'thit ga', quantity: '200', unit: 'gram', isOptional: false },
      { name: 'Nấm', normalized_name: 'nam', quantity: '80', unit: 'gram', isOptional: false },
      { name: 'Cà rốt', normalized_name: 'ca rot', quantity: '1/2', unit: 'củ', isOptional: true },
      { name: 'Gừng', normalized_name: 'gung', quantity: '1', unit: 'nhánh', isOptional: true },
      { name: 'Hành lá', normalized_name: 'hanh la', quantity: '2', unit: 'nhánh', isOptional: true },
    ],
    ingredientKeywords: ['gạo', 'thịt gà', 'ức gà', 'đùi gà', 'nấm', 'cà rốt', 'gừng', 'hành lá'],
    instructions: [
      { stepNumber: 1, instruction: 'Gà cắt miếng vừa ăn, ướp với chút hạt nêm, tiêu, gừng băm và dầu hào 10 phút.' },
      { stepNumber: 2, instruction: 'Vo gạo sạch cho vào nồi cơm điện, đong lượng nước vừa đủ như nấu cơm bình thường.' },
      { stepNumber: 3, instruction: 'Xếp thịt gà, nấm và cà rốt thái hạt lựu lên trên mặt gạo. Đậy nắp bấm nút Cook.' },
      { stepNumber: 4, instruction: 'Khi nồi bật nút Warm, mở nắp rắc hành lá cắt nhỏ, xới đều và thưởng thức ngay.' },
    ],
  },
  {
    title: 'Canh Kim Chi Đậu Phụ Thịt Heo',
    description: 'Nước canh cay ấm nồng, kim chi giòn chua và đậu hũ mềm tan cho ngày se lạnh.',
    imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?q=80&w=800',
    prepTimeMinutes: 5,
    cookTimeMinutes: 12,
    servings: 3,
    difficulty: 'EASY',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Kim chi', normalized_name: 'kim chi', quantity: '150', unit: 'gram', isOptional: false },
      { name: 'Thịt heo', normalized_name: 'thit heo', quantity: '150', unit: 'gram', isOptional: false },
      { name: 'Đậu phụ', normalized_name: 'dau phu', quantity: '2', unit: 'miếng', isOptional: false },
      { name: 'Hành lá', normalized_name: 'hanh la', quantity: '2', unit: 'nhánh', isOptional: true },
      { name: 'Tỏi', normalized_name: 'toi', quantity: '2', unit: 'tép', isOptional: true },
    ],
    ingredientKeywords: ['kim chi', 'thịt heo', 'thịt ba chỉ', 'đậu phụ', 'đậu hũ', 'hành lá', 'tỏi'],
    instructions: [
      { stepNumber: 1, instruction: 'Thịt heo cắt lát mỏng. Kim chi cắt khúc vừa ăn. Đậu phụ cắt miếng vuông.' },
      { stepNumber: 2, instruction: 'Phi thơm tỏi băm, cho thịt heo vào xào săn, tiếp tục cho kim chi vào đảo đều 2 phút.' },
      { stepNumber: 3, instruction: 'Đổ 500ml nước lọc và 3 thìa nước cốt kim chi vào đun sôi bùng lên.' },
      { stepNumber: 4, instruction: 'Thả đậu phụ vào nấu thêm 3 phút, nêm chút hạt nêm vừa ăn, rắc hành lá rồi tắt bếp.' },
    ],
  },
  {
    title: 'Cơm Chiên Trứng Xúc Xích',
    description: 'Món vét cơm nguội siêu tốc, thơm lừng giòn hạt cho bữa ăn nhanh gọn.',
    imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?q=80&w=800',
    prepTimeMinutes: 5,
    cookTimeMinutes: 10,
    servings: 2,
    difficulty: 'EASY',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Cơm nguội', normalized_name: 'com nguoi', quantity: '2', unit: 'chén', isOptional: false },
      { name: 'Trứng gà', normalized_name: 'trung ga', quantity: '2', unit: 'quả', isOptional: false },
      { name: 'Xúc xích', normalized_name: 'xuc xich', quantity: '2', unit: 'cây', isOptional: false },
      { name: 'Hành lá', normalized_name: 'hanh la', quantity: '2', unit: 'nhánh', isOptional: false },
      { name: 'Cà rốt', normalized_name: 'ca rot', quantity: '1/2', unit: 'củ', isOptional: true },
    ],
    ingredientKeywords: ['cơm nguội', 'cơm', 'trứng', 'trứng gà', 'xúc xích', 'hành lá', 'cà rốt'],
    instructions: [
      { stepNumber: 1, instruction: 'Xúc xích và cà rốt thái hạt lựu. Hành lá cắt nhỏ.' },
      { stepNumber: 2, instruction: 'Đập 1 quả trứng trộn đều trực tiếp vào tô cơm nguội cho hạt cơm vàng óng.' },
      { stepNumber: 3, instruction: 'Phi thơm đầu hành, cho xúc xích và cà rốt vào xào săn lại rồi vớt ra.' },
      { stepNumber: 4, instruction: 'Đổ cơm vào đảo lửa lớn cho săn hạt, thêm quả trứng còn lại và xúc xích vào, nêm nước tương, rắc hành lá.' },
    ],
  },
  {
    title: 'Trứng Hấp Kiểu Hàn Lò Vi Sóng',
    description: 'Trứng hấp mềm mịn bồng bềnh, thơm béo phô mai chỉ mất 3 phút với lò vi sóng.',
    imageUrl: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?q=80&w=800',
    prepTimeMinutes: 2,
    cookTimeMinutes: 3,
    servings: 1,
    difficulty: 'EASY',
    appliance: 'MICROWAVE',
    ingredients: [
      { name: 'Trứng gà', normalized_name: 'trung ga', quantity: '2', unit: 'quả', isOptional: false },
      { name: 'Hành lá', normalized_name: 'hanh la', quantity: '1', unit: 'nhánh', isOptional: false },
      { name: 'Phô mai', normalized_name: 'pho mai', quantity: '1', unit: 'lát', isOptional: true },
      { name: 'Nước mắm', normalized_name: 'nuoc mam', quantity: '1/2', unit: 'muỗng cà phê', isOptional: true },
    ],
    ingredientKeywords: ['trứng gà', 'trứng', 'hành lá', 'phô mai', 'nước mắm'],
    instructions: [
      { stepNumber: 1, instruction: 'Đập trứng vào cốc sứ hoặc tô chịu nhiệt, thêm 50ml nước lọc, nước mắm và hành lá cắt nhỏ rồi đánh đều.' },
      { stepNumber: 2, instruction: 'Đặt 1 lát phô mai lên trên cùng, bọc màng bọc thực phẩm và chọc vài lỗ thoát hơi.' },
      { stepNumber: 3, instruction: 'Quay lò vi sóng công suất trung bình cao trong 2.5 - 3 phút đến khi trứng nở phồng mềm mịn.' },
    ],
  },
  {
    title: 'Khoai Lang Nướng Nồi Chiên Không Dầu',
    description: 'Khoai lang mật nướng ứa mật dẻo quánh, thơm lừng ngọt lịm cho bữa phụ healthy.',
    imageUrl: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?q=80&w=800',
    prepTimeMinutes: 5,
    cookTimeMinutes: 30,
    servings: 2,
    difficulty: 'EASY',
    appliance: 'AIRFRYER',
    ingredients: [
      { name: 'Khoai lang', normalized_name: 'khoai lang', quantity: '3', unit: 'củ', isOptional: false },
      { name: 'Bơ', normalized_name: 'bo', quantity: '10', unit: 'gram', isOptional: true },
    ],
    ingredientKeywords: ['khoai lang', 'bơ'],
    instructions: [
      { stepNumber: 1, instruction: 'Khoai lang rửa sạch vỏ, để ráo nước hoặc thấm khô.' },
      { stepNumber: 2, instruction: 'Xếp khoai vào nồi chiên không dầu, nướng ở 180°C trong 20 phút.' },
      { stepNumber: 3, instruction: 'Lật mặt khoai nướng tiếp ở 200°C trong 10-15 phút đến khi vỏ phồng, mật tơi chảy ra.' },
    ],
  },
  {
    title: 'Ức Gà Áp Chảo Rau Củ Eat Clean',
    description: 'Ức gà mềm ngọt không hề khô xác, ăn kèm bông cải và ớt chuông thanh đạm.',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800',
    prepTimeMinutes: 10,
    cookTimeMinutes: 10,
    servings: 1,
    difficulty: 'EASY',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Thịt gà', normalized_name: 'thit ga', quantity: '200', unit: 'gram', isOptional: false },
      { name: 'Bông cải', normalized_name: 'bong cai', quantity: '100', unit: 'gram', isOptional: false },
      { name: 'Ớt chuông', normalized_name: 'ot chuong', quantity: '1/2', unit: 'quả', isOptional: true },
      { name: 'Tỏi', normalized_name: 'toi', quantity: '2', unit: 'tép', isOptional: true },
      { name: 'Tiêu', normalized_name: 'tieu', quantity: '1/2', unit: 'muỗng cà phê', isOptional: true },
    ],
    ingredientKeywords: ['thịt gà', 'ức gà', 'bông cải', 'súp lơ', 'ớt chuông', 'tỏi', 'tiêu'],
    instructions: [
      { stepNumber: 1, instruction: 'Ức gà khía nhẹ mặt, ướp với chút muối, tiêu và tỏi băm 10 phút.' },
      { stepNumber: 2, instruction: 'Bông cải và ớt chuông chần sơ qua nước sôi 1 phút rồi vớt ra ngâm nước lạnh.' },
      { stepNumber: 3, instruction: 'Quét 1 lớp dầu ô liu lên chảo, áp chảo ức gà mỗi mặt 4-5 phút trên lửa vừa cho chín vàng thơm.' },
      { stepNumber: 4, instruction: 'Cho bông cải và ớt chuông vào đảo nhanh 1 phút rồi bày ra đĩa ăn kèm sốt mè rang.' },
    ],
  },
  {
    title: 'Canh Trứng Cà Chua (Canh Mây)',
    description: 'Bát canh ngọt mát, nhẹ bụng chỉ mất 5 phút nấu từ trứng và cà chua.',
    imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?q=80&w=800',
    prepTimeMinutes: 3,
    cookTimeMinutes: 5,
    servings: 3,
    difficulty: 'EASY',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Trứng gà', normalized_name: 'trung ga', quantity: '2', unit: 'quả', isOptional: false },
      { name: 'Cà chua', normalized_name: 'ca chua', quantity: '2', unit: 'quả', isOptional: false },
      { name: 'Hành lá', normalized_name: 'hanh la', quantity: '2', unit: 'nhánh', isOptional: false },
      { name: 'Hành tím', normalized_name: 'hanh tim', quantity: '1', unit: 'củ', isOptional: true },
    ],
    ingredientKeywords: ['trứng', 'trứng gà', 'cà chua', 'hành lá', 'hành tím'],
    instructions: [
      { stepNumber: 1, instruction: 'Cà chua rửa sạch cắt múi cau. Trứng đánh tan trong chén.' },
      { stepNumber: 2, instruction: 'Phi thơm hành tím, cho cà chua vào xào mềm tạo màu đỏ đẹp mắt.' },
      { stepNumber: 3, instruction: 'Đổ 500ml nước vào đun sôi, nêm 1 thìa hạt nêm và nước mắm vừa ăn.' },
      { stepNumber: 4, instruction: 'Hạ lửa nhỏ, đổ từ từ trứng vào nồi đồng thời khuấy nhẹ theo 1 chiều tạo vân mây đẹp mắt, rắc hành lá tắt bếp.' },
    ],
  },
  {
    title: 'Thịt Heo Kho Tiêu Đậm Đà',
    description: 'Thịt ba chỉ thơm béo ngậy, sốt tiêu đen cay nồng ăn cùng cơm nóng tuyệt hảo.',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=800',
    prepTimeMinutes: 10,
    cookTimeMinutes: 20,
    servings: 3,
    difficulty: 'MEDIUM',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Thịt heo', normalized_name: 'thit heo', quantity: '350', unit: 'gram', isOptional: false },
      { name: 'Hành tím', normalized_name: 'hanh tim', quantity: '2', unit: 'củ', isOptional: false },
      { name: 'Tỏi', normalized_name: 'toi', quantity: '3', unit: 'tép', isOptional: false },
      { name: 'Hành lá', normalized_name: 'hanh la', quantity: '2', unit: 'nhánh', isOptional: true },
      { name: 'Tiêu', normalized_name: 'tieu', quantity: '1', unit: 'muỗng canh', isOptional: true },
      { name: 'Ớt', normalized_name: 'ot', quantity: '1', unit: 'quả', isOptional: true },
    ],
    ingredientKeywords: ['thịt heo', 'thịt lợn', 'thịt ba chỉ', 'hành tím', 'tỏi', 'hành lá', 'tiêu', 'ớt'],
    instructions: [
      { stepNumber: 1, instruction: 'Thịt heo rửa sạch, cắt miếng con chì vừa ăn. Ướp với hành tỏi băm, nước mắm, đường, tiêu 15 phút.' },
      { stepNumber: 2, instruction: 'Thắng 1 thìa đường với chút dầu ăn trên chảo cho đến khi có màu cánh gián đẹp mắt.' },
      { stepNumber: 3, instruction: 'Cho thịt vào đảo săn đều với lửa lớn cho ngấm màu nước hàng.' },
      { stepNumber: 4, instruction: 'Thêm chút nước xâm xấp mặt thịt, hạ nhỏ lửa đun liu riu 15 phút đến khi nước sốt keo lại, rắc nhiều tiêu và hành lá.' },
    ],
  },
  {
    title: 'Canh Rau Cải Thịt Băm',
    description: 'Bát canh rau thanh mát, ngọt nước từ thịt băm cho ngày bận rộn.',
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?q=80&w=800',
    prepTimeMinutes: 5,
    cookTimeMinutes: 8,
    servings: 3,
    difficulty: 'EASY',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Rau cải', normalized_name: 'rau cai', quantity: '1', unit: 'bó', isOptional: false },
      { name: 'Thịt băm', normalized_name: 'thit bam', quantity: '100', unit: 'gram', isOptional: false },
      { name: 'Hành tím', normalized_name: 'hanh tim', quantity: '1', unit: 'củ', isOptional: true },
      { name: 'Gừng', normalized_name: 'gung', quantity: '1', unit: 'nhánh nhỏ', isOptional: true },
    ],
    ingredientKeywords: ['rau cải', 'thịt băm', 'thịt heo', 'hành tím', 'gừng'],
    instructions: [
      { stepNumber: 1, instruction: 'Rau cải nhặt rửa sạch, cắt khúc 3cm. Gừng thái sợi nhỏ.' },
      { stepNumber: 2, instruction: 'Thịt băm ướp chút hạt nêm và hành tím băm.' },
      { stepNumber: 3, instruction: 'Xào săn thịt băm với chút dầu ăn, sau đó đổ 600ml nước vào đun sôi.' },
      { stepNumber: 4, instruction: 'Nước sôi thả rau cải và vài sợi gừng vào, đun sôi lại 2 phút là rau chín ngọt, nêm nếm vừa ăn rồi tắt bếp.' },
    ],
  },
  {
    title: 'Mì Tôm Xào Trứng Bắp Cải',
    description: 'Nâng cấp gói mì tôm quen thuộc thành đĩa mì xào giòn ngọt đậm đà siêu bắt mắt.',
    imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800',
    prepTimeMinutes: 5,
    cookTimeMinutes: 7,
    servings: 1,
    difficulty: 'EASY',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Mì tôm', normalized_name: 'mi tom', quantity: '1', unit: 'gói', isOptional: false },
      { name: 'Trứng gà', normalized_name: 'trung ga', quantity: '1', unit: 'quả', isOptional: false },
      { name: 'Bắp cải', normalized_name: 'bap cai', quantity: '100', unit: 'gram', isOptional: false },
      { name: 'Hành lá', normalized_name: 'hanh la', quantity: '1', unit: 'nhánh', isOptional: true },
      { name: 'Tỏi', normalized_name: 'toi', quantity: '1', unit: 'tép', isOptional: true },
    ],
    ingredientKeywords: ['mì tôm', 'mì gói', 'trứng', 'trứng gà', 'bắp cải', 'hành lá', 'tỏi'],
    instructions: [
      { stepNumber: 1, instruction: 'Trần sơ mì tôm qua nước sôi 1 phút cho sợi mì vừa tơi rồi vớt ra xả nước lạnh để ráo.' },
      { stepNumber: 2, instruction: 'Bắp cải thái sợi mỏng rửa sạch. Đập trứng ra chén đánh tan.' },
      { stepNumber: 3, instruction: 'Phi thơm tỏi, cho bắp cải vào xào nhanh tay, đổ trứng vào đảo đều cho bám bắp cải.' },
      { stepNumber: 4, instruction: 'Cho sợi mì vào đảo lửa lớn cùng 1/2 gói gia vị mì và chút nước tương, rắc hành lá rồi tắt bếp.' },
    ],
  },
];

module.exports = recipes;
