/**
 * Comprehensive Vietnamese Family & Everyday Meal Recipes for Vét Tủ (ChefMatch)
 * Covers breakfast, lunch combos, dinner combos, traditional soups, braises, stir-fries.
 */

const vietnameseFamilyRecipes = [
  {
    title: 'Bánh Mì Ốp La Xúc Xích',
    description: 'Bữa sáng quốc dân giòn rụm, trứng lòng đào béo ngậy kèm xúc xích nướng thơm lừng.',
    imageUrl: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?q=80&w=800',
    prepTimeMinutes: 5,
    cookTimeMinutes: 8,
    servings: 1,
    difficulty: 'EASY',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Bánh mì', normalized_name: 'banh mi', quantity: '1', unit: 'ổ', isOptional: false },
      { name: 'Trứng gà', normalized_name: 'trung ga', quantity: '2', unit: 'quả', isOptional: false },
      { name: 'Xúc xích', normalized_name: 'xuc xich', quantity: '1', unit: 'cây', isOptional: false },
      { name: 'Dưa leo', normalized_name: 'dua leo', quantity: '1/2', unit: 'trái', isOptional: true },
      { name: 'Ngò rí', normalized_name: 'ngo ri', quantity: '1', unit: 'nhánh', isOptional: true },
      { name: 'Nước tương hoặc tương ớt', normalized_name: 'nuoc tuong', quantity: '1', unit: 'muỗng cà phê', isOptional: true },
    ],
    ingredientKeywords: ['bánh mì', 'trứng gà', 'trứng', 'xúc xích', 'dưa leo', 'ngò rí'],
    instructions: [
      { stepNumber: 1, instruction: 'Bánh mì làm nóng trong chảo hoặc nồi chiên không dầu 2 phút cho giòn.' },
      { stepNumber: 2, instruction: 'Khía nhẹ xúc xích, chiên vàng đều hai mặt rồi vớt ra.' },
      { stepNumber: 3, instruction: 'Đập 2 quả trứng gà vào chảo dầu nóng, rắc chút tiêu, chiên lòng đào rồi tắt bếp.' },
      { stepNumber: 4, instruction: 'Kẹp trứng, xúc xích và dưa leo thái lát vào bánh mì, chan nước tương hoặc tương ớt tùy thích.' },
    ],
  },
  {
    title: 'Phở Bò Tái Lăn',
    description: 'Bát phở bò nóng hổi thơm nức mùi gừng tỏi xào lăn cùng nước dùng thanh ngọt đậm đà.',
    imageUrl: 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?q=80&w=800',
    prepTimeMinutes: 15,
    cookTimeMinutes: 20,
    servings: 2,
    difficulty: 'MEDIUM',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Bánh phở tươi', normalized_name: 'banh pho', quantity: '400', unit: 'gram', isOptional: false },
      { name: 'Thịt bò thăn', normalized_name: 'thit bo', quantity: '250', unit: 'gram', isOptional: false },
      { name: 'Nước dùng bò/xương', normalized_name: 'nuoc dung', quantity: '800', unit: 'ml', isOptional: false },
      { name: 'Hành lá', normalized_name: 'hanh la', quantity: '3', unit: 'nhánh', isOptional: false },
      { name: 'Gừng', normalized_name: 'gung', quantity: '1', unit: 'củ nhỏ', isOptional: false },
      { name: 'Tỏi', normalized_name: 'toi', quantity: '4', unit: 'tép', isOptional: false },
      { name: 'Hành tây', normalized_name: 'hanh tay', quantity: '1/2', unit: 'củ', isOptional: true },
    ],
    ingredientKeywords: ['phở', 'bánh phở', 'thịt bò', 'hành lá', 'gừng', 'tỏi', 'hành tây', 'nước dùng'],
    instructions: [
      { stepNumber: 1, instruction: 'Thịt bò thái mỏng, ướp chút gừng băm, tỏi băm, hạt nêm và 1 thìa dầu ăn.' },
      { stepNumber: 2, instruction: 'Đun sôi nồi nước dùng bò, nêm thêm hoa hồi, quế, hành nướng cho dậy mùi thơm nức.' },
      { stepNumber: 3, instruction: 'Bắc chảo lửa lớn, phi thơm tỏi băm, cho thịt bò vào xào lăn nhanh tay 1 phút rồi trút ra tô.' },
      { stepNumber: 4, instruction: 'Trần bánh phở xếp vào tô, cho thịt bò xào lăn, hành hoa, hành tây thái mỏng lên rồi chan nước dùng sôi sùng sục.' },
    ],
  },
  {
    title: 'Bún Thịt Nướng / Bún Chả Giò',
    description: 'Bún tươi mát ăn kèm chả giò giòn rụm, thịt nướng thơm lừng và nước mắm chua ngọt chuẩn vị.',
    imageUrl: 'https://images.unsplash.com/photo-1503764654157-72d979d9af2f?q=80&w=800',
    prepTimeMinutes: 15,
    cookTimeMinutes: 15,
    servings: 2,
    difficulty: 'EASY',
    appliance: 'AIRFRYER',
    ingredients: [
      { name: 'Bún tươi', normalized_name: 'bun tuoi', quantity: '400', unit: 'gram', isOptional: false },
      { name: 'Chả giò (Nem rán)', normalized_name: 'cha gio', quantity: '6', unit: 'cái', isOptional: false },
      { name: 'Thịt heo nạc dăm', normalized_name: 'thit heo', quantity: '200', unit: 'gram', isOptional: true },
      { name: 'Rau sống (xà lách, rau thơm)', normalized_name: 'rau song', quantity: '1', unit: 'dĩa', isOptional: false },
      { name: 'Đậu phộng rang', normalized_name: 'dau phong', quantity: '2', unit: 'muỗng canh', isOptional: true },
      { name: 'Nước mắm chua ngọt', normalized_name: 'nuoc mam', quantity: '1', unit: 'chén', isOptional: false },
    ],
    ingredientKeywords: ['bún tươi', 'bún', 'chả giò', 'thịt nướng', 'thịt heo', 'rau sống', 'đậu phộng'],
    instructions: [
      { stepNumber: 1, instruction: 'Cho chả giò vào nồi chiên không dầu nướng ở 180°C trong 12-15 phút đến khi vàng giòn.' },
      { stepNumber: 2, instruction: 'Rau sống rửa sạch, cắt nhỏ lót dưới đáy tô.' },
      { stepNumber: 3, instruction: 'Cho bún tươi lên trên, cắt chả giò giòn rụm xếp vòng quanh.' },
      { stepNumber: 4, instruction: 'Rắc mỡ hành, đậu phộng rang giã dập và chan nước mắm chua ngọt tỏi ớt trộn đều thưởng thức.' },
    ],
  },
  {
    title: 'Bún Bò Huế Gia Truyền',
    description: 'Tô bún bò Huế đậm đà thơm nồng mùi sả, ớt sa tế cay xé lưỡi cùng bắp bò mềm ngọt.',
    imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800',
    prepTimeMinutes: 20,
    cookTimeMinutes: 30,
    servings: 3,
    difficulty: 'MEDIUM',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Bún sợi to', normalized_name: 'bun soi to', quantity: '500', unit: 'gram', isOptional: false },
      { name: 'Bắp bò', normalized_name: 'bap bo', quantity: '300', unit: 'gram', isOptional: false },
      { name: 'Sả tươi', normalized_name: 'sa', quantity: '4', unit: 'cây', isOptional: false },
      { name: 'Mắm ruốc Huế', normalized_name: 'mam ruoc', quantity: '1', unit: 'muỗng canh', isOptional: false },
      { name: 'Ớt sa tế', normalized_name: 'ot sa te', quantity: '1', unit: 'muỗng canh', isOptional: true },
      { name: 'Rau bắp chuối, rau muống chẻ', normalized_name: 'rau bap chuoi', quantity: '1', unit: 'dĩa', isOptional: true },
    ],
    ingredientKeywords: ['bún bò', 'bún bò huế', 'bắp bò', 'thịt bò', 'sả', 'mắm ruốc', 'sa tế'],
    instructions: [
      { stepNumber: 1, instruction: 'Bắp bò cuộn tròn luộc chín tới cùng sả đập dập, vớt ra ngâm nước lạnh rồi thái lát mỏng.' },
      { stepNumber: 2, instruction: 'Hòa mắm ruốc với nước lạnh, lóng lấy nước trong đổ vào nồi nước luộc thịt.' },
      { stepNumber: 3, instruction: 'Phi thơm dầu màu điều với sả băm, ớt sa tế rồi trút vào nồi nước dùng cho đỏ au thơm phức.' },
      { stepNumber: 4, instruction: 'Trần bún xếp vào tô cùng bắp bò thái lát, hành ngò, chan nước dùng cay nồng ngập bún.' },
    ],
  },
  {
    title: 'Bún Riêu Cua Đồng',
    description: 'Vị chua thanh mát của giấm bỗng, riêu cua béo mềm hòa quyện đậu hũ rán vàng óng.',
    imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?q=80&w=800',
    prepTimeMinutes: 15,
    cookTimeMinutes: 20,
    servings: 3,
    difficulty: 'MEDIUM',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Bún tươi', normalized_name: 'bun tuoi', quantity: '500', unit: 'gram', isOptional: false },
      { name: 'Cua đồng xay', normalized_name: 'cua dong', quantity: '300', unit: 'gram', isOptional: false },
      { name: 'Cà chua', normalized_name: 'ca chua', quantity: '3', unit: 'quả', isOptional: false },
      { name: 'Đậu hũ', normalized_name: 'dau hu', quantity: '2', unit: 'miếng', isOptional: false },
      { name: 'Hành lá, tía tô, kinh giới', normalized_name: 'hanh la', quantity: '1', unit: 'bó', isOptional: false },
      { name: 'Giấm bỗng hoặc me', normalized_name: 'giam bong', quantity: '2', unit: 'muỗng canh', isOptional: true },
    ],
    ingredientKeywords: ['bún riêu', 'bún riêu cua', 'cua đồng', 'đậu hũ', 'cà chua', 'giấm bỗng'],
    instructions: [
      { stepNumber: 1, instruction: 'Cua đồng lọc lấy nước thịt, đun lửa vừa khuấy đều tay cho riêu cua đóng bánh nổi lên mặt rồi vớt riêng.' },
      { stepNumber: 2, instruction: 'Đậu hũ cắt miếng vuông chiên giòn vàng đều.' },
      { stepNumber: 3, instruction: 'Xào cà chua bổ múi cau với dầu hạt điều tạo màu đỏ đẹp, trút vào nồi nước cua cùng giấm bỗng nêm vừa vị.' },
      { stepNumber: 4, instruction: 'Xếp bún vào tô, múc riêu cua, đậu rán, cà chua lên trên rồi chan nước riêu nóng thơm.' },
    ],
  },
  {
    title: 'Cháo Sườn Trứng Bắc Thảo',
    description: 'Cháo sánh mịn thơm ngọt từ xương sườn, quyện vị bùi béo đặc trưng của trứng bắc thảo.',
    imageUrl: 'https://images.unsplash.com/photo-1541832676-9b763b0239ab?q=80&w=800',
    prepTimeMinutes: 10,
    cookTimeMinutes: 30,
    servings: 2,
    difficulty: 'EASY',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Gạo tẻ & gạo nếp', normalized_name: 'gao', quantity: '100', unit: 'gram', isOptional: false },
      { name: 'Sườn non heo', normalized_name: 'suon heo', quantity: '200', unit: 'gram', isOptional: false },
      { name: 'Trứng bắc thảo', normalized_name: 'trung bac thao', quantity: '2', unit: 'quả', isOptional: false },
      { name: 'Hành hoa, gừng tươi', normalized_name: 'hanh hoa', quantity: '1', unit: 'ít', isOptional: true },
      { name: 'Quẩy giòn', normalized_name: 'quay', quantity: '2', unit: 'cái', isOptional: true },
    ],
    ingredientKeywords: ['cháo', 'cháo sườn', 'sườn heo', 'trứng bắc thảo', 'gạo', 'gừng'],
    instructions: [
      { stepNumber: 1, instruction: 'Sườn chần sơ nước sôi, ninh với gạo và vài lát gừng trong 30 phút đến khi cháo nở sánh mịn.' },
      { stepNumber: 2, instruction: 'Trứng bắc thảo lột vỏ, cắt múi cau nhỏ.' },
      { stepNumber: 3, instruction: 'Nêm vào cháo hạt nêm, nước mắm ngon và tiêu sọ xay vừa khẩu vị.' },
      { stepNumber: 4, instruction: 'Múc cháo ra tô, xếp sườn xé nhỏ và trứng bắc thảo lên trên, rắc hành lá và ăn cùng quẩy.' },
    ],
  },
  {
    title: 'Bánh Mì Xíu Mại Sốt Cà Chua',
    description: 'Viên xíu mại mềm tan thơm mùi củ năng, sốt cà chua sền sệt chấm bánh mì nóng giòn tuyệt hảo.',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=800',
    prepTimeMinutes: 15,
    cookTimeMinutes: 20,
    servings: 2,
    difficulty: 'EASY',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Thịt heo xay có mỡ', normalized_name: 'thit heo xay', quantity: '250', unit: 'gram', isOptional: false },
      { name: 'Cà chua chín', normalized_name: 'ca chua', quantity: '3', unit: 'quả', isOptional: false },
      { name: 'Bánh mì', normalized_name: 'banh mi', quantity: '2', unit: 'ổ', isOptional: false },
      { name: 'Củ năng hoặc hành tây', normalized_name: 'cu nang', quantity: '50', unit: 'gram', isOptional: true },
      { name: 'Tỏi băm, hành tím', normalized_name: 'toi bam', quantity: '2', unit: 'tép', isOptional: true },
    ],
    ingredientKeywords: ['bánh mì', 'xíu mại', 'thịt băm', 'thịt heo', 'cà chua', 'củ năng'],
    instructions: [
      { stepNumber: 1, instruction: 'Trộn thịt xay với củ năng băm nhỏ, tiêu, đường, hạt nêm, vo thành từng viên tròn rồi hấp chín 10 phút.' },
      { stepNumber: 2, instruction: 'Cà chua băm nhỏ. Phi thơm tỏi xào cà chua thành sốt sệt đỏ mọng.' },
      { stepNumber: 3, instruction: 'Đổ nước hấp xíu mại và các viên xíu mại vào sốt cà chua, đun lửa liu riu 10 phút cho ngấm gia vị.' },
      { stepNumber: 4, instruction: 'Múc xíu mại ra chén, rắc tiêu ngò rí và chấm bánh mì giòn tan nóng hổi.' },
    ],
  },
  {
    title: 'Thịt Heo Rang Cháy Cạnh + Canh Cải Ngọt Thịt Băm',
    description: 'Bữa cơm trưa thân thuộc chuẩn vị mẹ nấu: thịt ba chỉ cháy cạnh xém vàng thơm ngậy và canh cải ngọt lịm.',
    imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?q=80&w=800',
    prepTimeMinutes: 10,
    cookTimeMinutes: 18,
    servings: 3,
    difficulty: 'EASY',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Thịt ba chỉ', normalized_name: 'thit ba chi', quantity: '300', unit: 'gram', isOptional: false },
      { name: 'Rau cải ngọt', normalized_name: 'rau cai ngot', quantity: '1', unit: 'bó', isOptional: false },
      { name: 'Thịt heo băm', normalized_name: 'thit bam', quantity: '80', unit: 'gram', isOptional: false },
      { name: 'Hành tím, hành lá', normalized_name: 'hanh tim', quantity: '2', unit: 'củ', isOptional: false },
      { name: 'Nước mắm, đường, tiêu', normalized_name: 'nuoc mam', quantity: '2', unit: 'muỗng canh', isOptional: false },
    ],
    ingredientKeywords: ['thịt ba chỉ', 'thịt rang cháy cạnh', 'canh cải ngọt', 'thịt băm', 'rau cải', 'hành tím'],
    instructions: [
      { stepNumber: 1, instruction: 'Thịt ba chỉ thái mỏng. Cho vào chảo không dầu đảo lửa vừa cho thịt tiết bớt mỡ và xém vàng đều các cạnh.' },
      { stepNumber: 2, instruction: 'Thêm hành tím thái lát, 1 thìa đường, 1.5 thìa nước mắm ngon và tiêu, đảo nhanh tay cho sốt keo óng ánh bám đều thịt.' },
      { stepNumber: 3, instruction: 'Nồi bên cạnh xào săn thịt băm với chút dầu ăn, đổ 600ml nước đun sôi.' },
      { stepNumber: 4, instruction: 'Nước sôi thả rau cải ngọt cắt khúc vào, nêm hạt nêm vừa ăn, đun sôi bùng 2 phút rồi tắt bếp.' },
    ],
  },
  {
    title: 'Gà Xào Sả Ớt + Canh Bí Đao Nấu Tôm',
    description: 'Thịt gà ta giòn dai thơm lừng mùi sả ớt cay tê, kết hợp canh bí đao tôm tươi thanh nhiệt giải ngấy.',
    imageUrl: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?q=80&w=800',
    prepTimeMinutes: 15,
    cookTimeMinutes: 20,
    servings: 3,
    difficulty: 'EASY',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Thịt gà ta', normalized_name: 'thit ga', quantity: '350', unit: 'gram', isOptional: false },
      { name: 'Sả băm, ớt tươi', normalized_name: 'sa bam', quantity: '3', unit: 'cây', isOptional: false },
      { name: 'Bí đao (Bí xanh)', normalized_name: 'bi dao', quantity: '1/2', unit: 'trái', isOptional: false },
      { name: 'Tôm tươi', normalized_name: 'tom tuoi', quantity: '100', unit: 'gram', isOptional: false },
      { name: 'Hành hoa, ngò rí', normalized_name: 'hanh hoa', quantity: '2', unit: 'nhánh', isOptional: true },
    ],
    ingredientKeywords: ['gà xào sả ớt', 'thịt gà', 'sả', 'ớt', 'canh bí đao', 'bí đao', 'tôm'],
    instructions: [
      { stepNumber: 1, instruction: 'Thịt gà chặt miếng vừa ăn, ướp chút hạt nêm, nước mắm, bột nghệ và 1/2 sả băm 15 phút.' },
      { stepNumber: 2, instruction: 'Phi thơm phần sả ớt còn lại trong chảo dầu nóng, trút thịt gà vào xào săn trên lửa lớn đến khi chín vàng thơm lừng.' },
      { stepNumber: 3, instruction: 'Tôm lột vỏ băm nhỏ, xào sơ rồi cho 700ml nước vào đun sôi.' },
      { stepNumber: 4, instruction: 'Thả bí đao thái lát vào nồi canh, nêm gia vị vừa ăn, bí trong thì rắc hành ngò tiêu rồi tắt bếp.' },
    ],
  },
  {
    title: 'Bò Xào Cần Tỏi + Canh Chua Cá Lóc',
    description: 'Món bò xào cần tỏi mềm ngọt giòn sần sật, ăn kèm bát canh chua cá lóc miền Tây chua thanh đậm đà.',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=800',
    prepTimeMinutes: 15,
    cookTimeMinutes: 20,
    servings: 3,
    difficulty: 'MEDIUM',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Thịt bò thăn', normalized_name: 'thit bo', quantity: '200', unit: 'gram', isOptional: false },
      { name: 'Cần tây, tỏi tây', normalized_name: 'can tay', quantity: '150', unit: 'gram', isOptional: false },
      { name: 'Cá lóc', normalized_name: 'ca loc', quantity: '250', unit: 'gram', isOptional: false },
      { name: 'Cà chua, thơm (dứa), dọc mùng', normalized_name: 'ca chua', quantity: '1', unit: 'phần', isOptional: false },
      { name: 'Nước cốt me, ngò gai, rau ngổ', normalized_name: 'me', quantity: '2', unit: 'muỗng', isOptional: false },
    ],
    ingredientKeywords: ['thịt bò', 'bò xào cần tỏi', 'cần tây', 'canh chua', 'canh chua cá lóc', 'cá lóc', 'dứa', 'cà chua'],
    instructions: [
      { stepNumber: 1, instruction: 'Thịt bò ướp tỏi băm, dầu hào, tiêu. Xào lửa lớn chín tới rồi trút riêng.' },
      { stepNumber: 2, instruction: 'Cho cần tỏi cắt khúc vào xào nhanh 1 phút, trút bò lại đảo đều rồi tắt bếp.' },
      { stepNumber: 3, instruction: 'Nấu nước sôi với cốt me, cho cá lóc vào nấu chín tới, vớt bọt.' },
      { stepNumber: 4, instruction: 'Thả cà chua, dứa, dọc mùng, giá đỗ vào nấu sôi lại, nêm nước mắm và rau ngổ, ngò gai thơm lừng.' },
    ],
  },
  {
    title: 'Tôm Rim Mặn Ngọt + Canh Rau Ngót Thịt Nạc',
    description: 'Tôm sông vỏ giòn óng ả đậm đà ngấm sốt mặn ngọt, canh rau ngót thịt băm ngọt mát thanh lọc cơ thể.',
    imageUrl: 'https://images.unsplash.com/photo-1559847844-5315695dadae?q=80&w=800',
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    servings: 3,
    difficulty: 'EASY',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Tôm tươi', normalized_name: 'tom tuoi', quantity: '300', unit: 'gram', isOptional: false },
      { name: 'Rau ngót', normalized_name: 'rau ngot', quantity: '1', unit: 'bó', isOptional: false },
      { name: 'Thịt nạc băm', normalized_name: 'thit bam', quantity: '80', unit: 'gram', isOptional: false },
      { name: 'Hành tím, tỏi', normalized_name: 'hanh tim', quantity: '2', unit: 'củ', isOptional: false },
      { name: 'Nước mắm, đường, tiêu', normalized_name: 'nuoc mam', quantity: '2', unit: 'muỗng canh', isOptional: false },
    ],
    ingredientKeywords: ['tôm rim', 'tôm rim mặn ngọt', 'tôm', 'canh rau ngót', 'rau ngót', 'thịt nạc'],
    instructions: [
      { stepNumber: 1, instruction: 'Tôm cắt bớt râu gai, rửa sạch. Phi tỏi thơm rồi trút tôm vào đảo đỏ au.' },
      { stepNumber: 2, instruction: 'Nêm 1.5 thìa đường, 1.5 thìa nước mắm, tiêu vào rim lửa nhỏ đến khi sốt keo bóng bám quanh tôm.' },
      { stepNumber: 3, instruction: 'Rau ngót tuốt lá, vò nhẹ cho mềm.' },
      { stepNumber: 4, instruction: 'Xào thơm thịt băm, cho 600ml nước đun sôi, thả rau ngót vào nêm vừa vị đun 3 phút là hoàn thành.' },
    ],
  },
  {
    title: 'Cá Basa Kho Tộ + Canh Cua Mồng Tơi Mướp',
    description: 'Cá kho tộ đượm màu cánh gián thơm nồng tiêu ớt, ăn cùng canh cua mồng tơi mướp ngọt mát ngày hè.',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=800',
    prepTimeMinutes: 15,
    cookTimeMinutes: 25,
    servings: 3,
    difficulty: 'MEDIUM',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Cá basa hoặc cá hú', normalized_name: 'ca basa', quantity: '350', unit: 'gram', isOptional: false },
      { name: 'Cua đồng xay', normalized_name: 'cua dong', quantity: '200', unit: 'gram', isOptional: false },
      { name: 'Rau mồng tơi, mướp hương', normalized_name: 'rau mong toi', quantity: '1', unit: 'bó', isOptional: false },
      { name: 'Nước màu, nước mắm, ớt', normalized_name: 'nuoc mau', quantity: '2', unit: 'muỗng', isOptional: false },
      { name: 'Hành tím, đầu hành', normalized_name: 'hanh tim', quantity: '2', unit: 'nhánh', isOptional: true },
    ],
    ingredientKeywords: ['cá kho', 'cá kho tộ', 'cá basa', 'canh cua', 'mồng tơi', 'mướp hương', 'cua đồng'],
    instructions: [
      { stepNumber: 1, instruction: 'Cá rửa sạch, ướp nước mắm, đường, nước màu, hành tím băm và tiêu 20 phút.' },
      { stepNumber: 2, instruction: 'Cho cá vào tộ kho lửa lớn sôi 3 phút rồi hạ lửa liu riu cho cá chắc thịt và sánh sốt.' },
      { stepNumber: 3, instruction: 'Lọc nước cua, đun sôi nhẹ cho riêu cua đóng bánh nổi lên.' },
      { stepNumber: 4, instruction: 'Thả mướp hương thái lát và rau mồng tơi vào nồi canh cua, nêm chút muối/hạt nêm đun sôi lại rồi tắt bếp.' },
    ],
  },
  {
    title: 'Sườn Non Xào Chua Ngọt + Canh Sườn Hầm Củ Quả',
    description: 'Sườn non xào chua ngọt óng ả quyến rũ, kèm canh sườn hầm cà rốt khoai tây bổ dưỡng thơm lừng.',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=800',
    prepTimeMinutes: 15,
    cookTimeMinutes: 25,
    servings: 3,
    difficulty: 'MEDIUM',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Sườn non heo', normalized_name: 'suon non', quantity: '400', unit: 'gram', isOptional: false },
      { name: 'Cà chua, ớt chuông, hành tây', normalized_name: 'ca chua', quantity: '1', unit: 'phần', isOptional: false },
      { name: 'Khoai tây, cà rốt', normalized_name: 'khoai tay', quantity: '1', unit: 'củ', isOptional: false },
      { name: 'Giấm, đường, tương cà, nước mắm', normalized_name: 'giam', quantity: '2', unit: 'muỗng canh', isOptional: false },
    ],
    ingredientKeywords: ['sườn xào chua ngọt', 'sườn non', 'canh sườn', 'cà rốt', 'khoai tây', 'ớt chuông'],
    instructions: [
      { stepNumber: 1, instruction: 'Sườn chặt miếng nhỏ, chần nước sôi. Chia 1/2 làm món xào, 1/2 đem ninh canh.' },
      { stepNumber: 2, instruction: 'Sườn làm chua ngọt đem chiên xém cạnh. Pha sốt: giấm, đường, tương cà, nước mắm.' },
      { stepNumber: 3, instruction: 'Phi tỏi, xào ớt chuông hành tây rồi cho sườn và sốt vào đảo đều lửa nhỏ cho sệt bóng.' },
      { stepNumber: 4, instruction: 'Phần sườn ninh canh cho cà rốt, khoai tây cắt khúc vào hầm 15 phút đến khi mềm ngọt.' },
    ],
  },
  {
    title: 'Đậu Phụ Nhồi Thịt Sốt Cà Chua + Canh Rau Muống Luộc',
    description: 'Bữa cơm trưa nhẹ nhàng: đậu phụ nhồi thịt mềm béo đượm sốt cà chua và nước rau muống vắt chanh mát rượi.',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800',
    prepTimeMinutes: 15,
    cookTimeMinutes: 18,
    servings: 3,
    difficulty: 'EASY',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Đậu phụ trắng', normalized_name: 'dau phu', quantity: '3', unit: 'miếng', isOptional: false },
      { name: 'Thịt heo xay', normalized_name: 'thit xay', quantity: '150', unit: 'gram', isOptional: false },
      { name: 'Mộc nhĩ (nấm mèo)', normalized_name: 'moc nhi', quantity: '2', unit: 'tai', isOptional: true },
      { name: 'Cà chua', normalized_name: 'ca chua', quantity: '2', unit: 'quả', isOptional: false },
      { name: 'Rau muống', normalized_name: 'rau muong', quantity: '1', unit: 'bó', isOptional: false },
      { name: 'Chanh tươi', normalized_name: 'chanh', quantity: '1', unit: 'quả', isOptional: true },
    ],
    ingredientKeywords: ['đậu phụ nhồi thịt', 'đậu nhồi thịt', 'đậu phụ', 'thịt băm', 'cà chua', 'rau muống', 'canh rau muống'],
    instructions: [
      { stepNumber: 1, instruction: 'Trộn thịt xay với mộc nhĩ băm nhỏ, tiêu, hạt nêm. Rạch bụng miếng đậu phụ rồi nhồi thịt vào.' },
      { stepNumber: 2, instruction: 'Chiên vàng mặt thịt và đậu phụ rồi vớt ra.' },
      { stepNumber: 3, instruction: 'Xào sốt cà chua nhuyễn, cho đậu nhồi thịt vào đun nhỏ lửa 10 phút cho ngấm đều sốt.' },
      { stepNumber: 4, instruction: 'Luộc rau muống xanh giòn vớt ra đĩa, nước luộc nêm chút muối/hạt nêm để nguội vắt chanh làm canh.' },
    ],
  },
  {
    title: 'Cánh Gà Chiên Nước Mắm + Canh Khoai Mỡ Tôm Băm',
    description: 'Cánh gà chiên vàng rộm sốt mắm tỏi thơm nức, ăn cùng bát canh khoai mỡ tím sánh dẻo ngọt tự nhiên.',
    imageUrl: 'https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?q=80&w=800',
    prepTimeMinutes: 15,
    cookTimeMinutes: 20,
    servings: 3,
    difficulty: 'EASY',
    appliance: 'AIRFRYER',
    ingredients: [
      { name: 'Cánh gà', normalized_name: 'canh ga', quantity: '400', unit: 'gram', isOptional: false },
      { name: 'Khoai mỡ tím', normalized_name: 'khoai mo', quantity: '250', unit: 'gram', isOptional: false },
      { name: 'Tôm tươi băm', normalized_name: 'tom bam', quantity: '100', unit: 'gram', isOptional: false },
      { name: 'Tỏi băm, ớt băm', normalized_name: 'toi bam', quantity: '1', unit: 'muỗng canh', isOptional: false },
      { name: 'Nước mắm, đường, bơ', normalized_name: 'nuoc mam', quantity: '2', unit: 'muỗng canh', isOptional: false },
      { name: 'Ngò om, ngò gai', normalized_name: 'ngo om', quantity: '1', unit: 'ít', isOptional: true },
    ],
    ingredientKeywords: ['cánh gà chiên nước mắm', 'cánh gà', 'gà chiên mắm', 'khoai mỡ', 'canh khoai mỡ', 'tôm'],
    instructions: [
      { stepNumber: 1, instruction: 'Cánh gà chiên trong nồi chiên không dầu ở 190°C trong 15 phút cho vàng giòn.' },
      { stepNumber: 2, instruction: 'Phi thơm tỏi ớt với chút bơ, cho nước mắm và đường vào nấu sệt lại rồi trút cánh gà vào đảo đều áo sốt.' },
      { stepNumber: 3, instruction: 'Khoai mỡ dùng muỗng nạo mịn.' },
      { stepNumber: 4, instruction: 'Xào thơm tôm băm, cho 600ml nước sôi, trút khoai mỡ vào khuấy đều đến khi canh sánh dẻo thơm, rắc ngò om ngò gai.' },
    ],
  },
  {
    title: 'Cá Điêu Hồng Chiên Xù Mắm Tỏi + Rau Cải Luộc',
    description: 'Cá điêu hồng giòn rụm bên ngoài, thịt ngọt mềm bên trong chấm mắm tỏi ớt cay nồng đậm đà.',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=800',
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    servings: 3,
    difficulty: 'EASY',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Cá điêu hồng', normalized_name: 'ca dieu hong', quantity: '1', unit: 'con (600g)', isOptional: false },
      { name: 'Rau cải ngọt hoặc cải thìa', normalized_name: 'rau cai', quantity: '1', unit: 'bó', isOptional: false },
      { name: 'Tỏi, ớt tươi', normalized_name: 'toi', quantity: '1', unit: 'củ', isOptional: false },
      { name: 'Nước mắm ngon, đường, chanh', normalized_name: 'nuoc mam', quantity: '2', unit: 'muỗng canh', isOptional: false },
    ],
    ingredientKeywords: ['cá chiên', 'cá điêu hồng', 'mắm tỏi', 'rau cải luộc', 'cải ngọt'],
    instructions: [
      { stepNumber: 1, instruction: 'Cá làm sạch khía vảy chéo, chiên ngập dầu trên lửa vừa đến khi da cá giòn rụm vàng ruộm.' },
      { stepNumber: 2, instruction: 'Giã nhuyễn tỏi ớt cùng 2 thìa đường, pha thêm 2 thìa nước mắm ngon và nước cốt chanh.' },
      { stepNumber: 3, instruction: 'Rau cải nhặt rửa sạch, luộc trong nước sôi có chút muối 2 phút vớt ra đĩa.' },
      { stepNumber: 4, instruction: 'Bày cá ra đĩa, ăn cùng rau cải luộc và chấm nước mắm tỏi ớt chua cay đậm vị.' },
    ],
  },
  {
    title: 'Bò Lúc Lắc Khoai Tây + Canh Rong Biển Đậu Phụ',
    description: 'Bò lúc lắc mềm ngọt sốt bơ tiêu đen kiểu Pháp - Việt, ăn cùng canh rong biển thanh mát bổ dưỡng.',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=800',
    prepTimeMinutes: 15,
    cookTimeMinutes: 15,
    servings: 2,
    difficulty: 'MEDIUM',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Thịt thăn bò', normalized_name: 'thit bo', quantity: '250', unit: 'gram', isOptional: false },
      { name: 'Ớt chuông, hành tây', normalized_name: 'ot chuong', quantity: '1', unit: 'phần', isOptional: false },
      { name: 'Khoai tây chiên', normalized_name: 'khoai tay', quantity: '100', unit: 'gram', isOptional: true },
      { name: 'Rong biển khô', normalized_name: 'rong bien', quantity: '10', unit: 'gram', isOptional: false },
      { name: 'Đậu hũ non', normalized_name: 'dau hu non', quantity: '1', unit: 'hộp', isOptional: false },
    ],
    ingredientKeywords: ['bò lúc lắc', 'thịt bò', 'khoai tây', 'ớt chuông', 'canh rong biển', 'đậu hũ'],
    instructions: [
      { stepNumber: 1, instruction: 'Thịt bò cắt khối vuông 2cm, ướp dầu hào, tỏi băm, tiêu đen, xì dầu và chút bơ.' },
      { stepNumber: 2, instruction: 'Bắc chảo thật nóng, trút thịt bò vào lắc đều tay lửa lớn 2 phút cùng ớt chuông, hành tây vuông.' },
      { stepNumber: 3, instruction: 'Rong biển ngâm nở cắt khúc. Đun sôi 600ml nước, thả rong biển và đậu hũ non cắt khối vào.' },
      { stepNumber: 4, instruction: 'Nêm chút hạt nêm và dầu mè cho canh rong biển thơm ngậy, dọn ăn kèm đĩa bò lúc lắc nóng hổi.' },
    ],
  },
  {
    title: 'Bò Cuộn Nấm Kim Châm Áp Chảo + Canh Cải Cúc',
    description: 'Thịt ba chỉ bò mềm ngọt cuộn nấm kim châm giòn sần sật đượm sốt xì dầu, canh cải cúc ngọt mát.',
    imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?q=80&w=800',
    prepTimeMinutes: 10,
    cookTimeMinutes: 12,
    servings: 2,
    difficulty: 'EASY',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Ba chỉ bò cuộn', normalized_name: 'ba chi bo', quantity: '200', unit: 'gram', isOptional: false },
      { name: 'Nấm kim châm', normalized_name: 'nam kim cham', quantity: '1', unit: 'gói (150g)', isOptional: false },
      { name: 'Rau cải cúc (tần ô)', normalized_name: 'rau cai cuc', quantity: '1', unit: 'bó', isOptional: false },
      { name: 'Thịt băm hoặc tôm khô', normalized_name: 'thit bam', quantity: '50', unit: 'gram', isOptional: true },
      { name: 'Xì dầu, dầu hào, tiêu', normalized_name: 'xi dau', quantity: '2', unit: 'muỗng', isOptional: false },
    ],
    ingredientKeywords: ['bò cuộn nấm', 'ba chỉ bò', 'nấm kim châm', 'canh cải cúc', 'tần ô'],
    instructions: [
      { stepNumber: 1, instruction: 'Trải từng lát ba chỉ bò, đặt cụm nấm kim châm vào cuộn chặt tay.' },
      { stepNumber: 2, instruction: 'Áp chảo các cuộn bò cho xém vàng các mặt, rưới sốt xì dầu dầu hào tiêu lên đảo đều 2 phút.' },
      { stepNumber: 3, instruction: 'Nấu sôi nước dùng thịt băm, thả rau cải cúc vào nêm gia vị vừa ăn.' },
      { stepNumber: 4, instruction: 'Cải cúc vừa chín tới tắt bếp ngay giữ màu xanh non mướt.' },
    ],
  },
  {
    title: 'Gỏi Gà Xé Phay Bắp Cải + Canh Gà Lá Giang',
    description: 'Gỏi gà chua ngọt the cay rau răm đưa cơm, kết hợp bát canh gà lá giang chua dịu bùng nổ vị giác.',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800',
    prepTimeMinutes: 15,
    cookTimeMinutes: 20,
    servings: 3,
    difficulty: 'MEDIUM',
    appliance: 'STOVE',
    ingredients: [
      { name: 'Thịt gà luộc', normalized_name: 'thit ga', quantity: '350', unit: 'gram', isOptional: false },
      { name: 'Bắp cải trắng hoặc tím', normalized_name: 'bap cai', quantity: '150', unit: 'gram', isOptional: false },
      { name: 'Lá giang tươi', normalized_name: 'la giang', quantity: '1', unit: 'bó nhỏ', isOptional: false },
      { name: 'Hành tây, rau răm', normalized_name: 'hanh tay', quantity: '1', unit: 'ít', isOptional: false },
      { name: 'Nước mắm chua ngọt, đậu phộng', normalized_name: 'nuoc mam', quantity: '3', unit: 'muỗng canh', isOptional: false },
    ],
    ingredientKeywords: ['gỏi gà', 'gà xé phay', 'bắp cải', 'canh lá giang', 'lá giang', 'thịt gà'],
    instructions: [
      { stepNumber: 1, instruction: 'Thịt gà luộc xé miếng vừa ăn. Lấy nước luộc gà để nấu canh.' },
      { stepNumber: 2, instruction: 'Bắp cải và hành tây bào mỏng ngâm nước đá cho giòn, vắt ráo trộn cùng gà xé, rau răm và nước mắm chua ngọt.' },
      { stepNumber: 3, instruction: 'Nước luộc gà đun sôi, vò nát lá giang thả vào cho ra vị chua thanh đặc trưng.' },
      { stepNumber: 4, instruction: 'Nêm chút nước mắm, đường cho canh đậm đà, múc ra tô rắc ngò gai ớt lát thưởng thức.' },
    ],
  },
];

module.exports = vietnameseFamilyRecipes;
